packages/varlet-ui/types/locale.d.ts
Fix bug generated by building in projects using vite and typescript.
"Type 'Locale' is not a constructor function type"
=> fix(cli): error when building with vite

packages/varlet-touch-emulator/iife.js, packages/varlet-touch-emulator/index.js
=> Use new Web Api standard features

packages/varlet-ui/src/form/Form.vue, packages/varlet-ui/src/input/Input.vue
=> perf(ui/inpuit): add class

packages/varlet-ui/src/rate/Rate.vue
=> perf(ui/rate): add call function

packages/varlet-ui/src/image-preview/ImagePreview.vue
=> perf(ui/image-preview): add class and call

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap, packages/varlet-ui/src/form/__tests__/index.spec.js, packages/varlet-ui/src/switch/Switch.vue, packages/varlet-ui/src/switch/__tests__/__snapshots__/index.spec.js.snap, packages/varlet-ui/src/switch/__tests__/index.spec.js, packages/varlet-ui/src/switch/switch.less
=> perf(ui/switch): add class

packages/varlet-ui/src/pagination/Pagination.vue, packages/varlet-ui/src/popup/Popup.tsx, packages/varlet-ui/src/pull-refresh/PullRefresh.vue
=> perf(ui/pull-refresh): add class

packages/varlet-cli/site/pc/components/LogoAnimation.vue, packages/varlet-cli/site/pc/pages/index.en-US.vue
=> fix: fix the `docs` logo position style

packages/varlet-ui/src/bottom-navigation/BottomNavigation.vue, packages/varlet-ui/src/bottom-navigation/__tests__/index.spec.js
`change` event repeat trigger, see [there](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFNuYWNrYmFyIH0gZnJvbSAnQHZhcmxldC91aSdcblxuY29uc3QgYWN0aXZlID0gcmVmKDApXG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAoYWN0aXZlKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd0aWdnZXInKVxuICBTbmFja2Jhci5pbmZvKGBjaGFuZ2VkIHRvICR7YWN0aXZlfWApXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8dmFyLWJvdHRvbS1uYXZpZ2F0aW9uIHYtbW9kZWw6YWN0aXZlPVwiYWN0aXZlXCIgQGNoYW5nZT1cImhhbmRsZUNoYW5nZVwiPlxuICAgIDx2YXItYm90dG9tLW5hdmlnYXRpb24taXRlbSBsYWJlbD1cIuagh+etvlwiIGljb249XCJob21lXCIgLz5cbiAgICA8dmFyLWJvdHRvbS1uYXZpZ2F0aW9uLWl0ZW0gbGFiZWw9XCLmoIfnrb5cIiBpY29uPVwibWFnbmlmeVwiIC8+XG4gICAgPHZhci1ib3R0b20tbmF2aWdhdGlvbi1pdGVtIGxhYmVsPVwi5qCH562+XCIgaWNvbj1cImhlYXJ0XCIgLz5cbiA …
=> fix(ui/BottomNavigation): change repeat trigger

packages/varlet-ui/src/collapse/Collapse.vue
由于`.var-collapse-item:before`中使用`z-index: -1`，当存在其他元素设置背景后，由于根层叠上下文原因会显示在背景之后，导致阴影显示出现问题。
- Varlet UI Playground中的样例请看[这里](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCB2YWx1ZSA9IHJlZihbJzEnXSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgc3R5bGU9XCJiYWNrZ3JvdW5kOndoaXRlXCI+XG4gICAgPHZhci1jb2xsYXBzZSB2LW1vZGVsPVwidmFsdWVcIj5cbiAgICA8dmFyLWNvbGxhcHNlLWl0ZW0gdGl0bGU9XCLmoIfpophcIiBuYW1lPVwiMVwiPuaWh+acrDwvdmFyLWNvbGxhcHNlLWl0ZW0+XG4gICAgPHZhci1jb2xsYXBzZS1pdGVtIHRpdGxlPVwi5qCH6aKYXCIgbmFtZT1cIjJcIj7mlofmnKw8L3Zhci1jb2xsYXBzZS1pdGVtPlxuICA8L3Zhci1jb2xsYXBzZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuPHN0eWxlPlxuPC9zdHlsZT5cbiIsIlBsYXlncm91bmQudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1x …
=> fix(ui/collapse): fix shadow invisibility of collapse

packages/varlet-cli/template/create/index.ts.ejs
---
修改当用tsx新建组件时，组件index.ts文件中引用组件文件后缀错误的问题
---
=> fix: error suffix when create tsx component

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap, packages/varlet-ui/src/option/option.less, packages/varlet-ui/src/select/Select.vue, packages/varlet-ui/src/select/__tests__/__snapshots__/index.spec.js.snap, packages/varlet-ui/src/select/docs/en-US.md, packages/varlet-ui/src/select/docs/zh-CN.md, packages/varlet-ui/src/select/example/index.vue, packages/varlet-ui/src/select/select.less, packages/varlet-ui/types/select.d.ts
---
Support `select` selected slots, can customize the selection style
---
=> feat(ui/select): support selected slot

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap, packages/varlet-ui/src/radio-group/__tests__/__snapshots__/index.spec.js.snap, packages/varlet-ui/src/radio/Radio.vue, packages/varlet-ui/src/radio/radio.less
---
---
add hover overlay for component radio
fix issue #899
=> feat: radio hover overlay and update snapshots

packages/varlet-vscode-extension/package.json, packages/varlet-vscode-extension/src/btn.ts, packages/varlet-vscode-extension/src/commands.ts, packages/varlet-vscode-extension/src/extension.ts, packages/varlet-vscode-extension/src/statusBarItems.ts
=> feat(vscode-extension): add `varlet documentation` and  `varlet playground`  btns

packages/varlet-ui/src/image-preview/ImagePreview.vue
---
---
I replicated this bug using varlet playground,  you can try it out. 
https://github.com/varletjs/varlet/assets/70570907/61abdd5e-5d52-42b1-86d3-2c19b04d96f7
https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHNob3dJbWFnZSA9IHJlZihmYWxzZSlcbmNvbnN0IGltYWdlTGlzdCA9IHJlZihbJ2h0dHBzOi8vdmFybGV0LmdpdGVlLmlvL3ZhcmxldC11aS9jYXQuanBnJ10pXG5cbmNvbnN0IHRvZ2dsZSA9ICgpID0+IHtcbiAgc2hvd0ltYWdlLnZhbHVlID0gIXNob3dJbWFnZS52YWx1ZVxufVxuXG5jb25zdCBoYW5kbGVDbGljayA9ICgpID0+IHtcbiAgY29uc29sZS5sb2coJ3lvdSBjbGlja2VkISEhJylcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgQGNsaWNrPVwiaGFuZGxlQ2xpY2tcIj5cbiAgICA8dmFyLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cInRvZ2dsZVwiPnRvZ2dsZTwvdmFyLWJ1dHRvbj5cbiA8dmFyLWltYWdlL …
=> fix(ui/image-preview): click can't trigger a close event sometimes

packages/varlet-ui/src/option/Option.vue
=> feat(select): add hover for option

packages/varlet-ui/src/checkbox-group/__tests__/__snapshots__/index.spec.js.snap, packages/varlet-ui/src/checkbox-group/__tests__/index.spec.js, packages/varlet-ui/src/checkbox-group/docs/en-US.md, packages/varlet-ui/src/checkbox-group/docs/zh-CN.md, packages/varlet-ui/src/checkbox-group/example/index.vue, packages/varlet-ui/src/checkbox-group/example/locale/en-US.ts, packages/varlet-ui/src/checkbox-group/example/locale/zh-CN.ts, packages/varlet-ui/src/checkbox/Checkbox.vue, packages/varlet-ui/src/checkbox/checkbox.less, packages/varlet-ui/src/checkbox/docs/en-US.md, packages/varlet-ui/src/checkbox/docs/zh-CN.md, packages/varlet-ui/src/checkbox/props.ts, packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap, packages/varlet-ui/types/checkbox.d.ts
=> feat(checkbox): support indeterminate status and slot

packages/varlet-ui/src/rate/Rate.vue, packages/varlet-ui/src/rate/props.ts, packages/varlet-ui/src/result/props.ts
=> refactor: simplify props definition and optimize types

README.md, README.zh-CN.md
Modified the `/README.md` and `README.zh-CN.md` to remove the link to CSDN IDE because of bad experience and possible damage to clickers.
While there are free credits, it's highly unlikely for most people to know that they have to manually close the instance.
=> docs: remove link to CSDN IDE in README.zh-CN.md

packages/varlet-ui/src/progress/Progress.vue, packages/varlet-ui/src/progress/docs/en-US.md, packages/varlet-ui/src/progress/docs/zh-CN.md
=> docs(progress): complete gradient color annotations

package.json, pnpm-lock.yaml
Add `overrides`
https://github.com/SukkaW/nolyfill/issues/21
[Speeding up the JavaScript ecosystem - Polyfills gone rogue](https://marvinh.dev/blog/speeding-up-javascript-ecosystem-part-6/ )
=> chore: using nolyfill reduce size

README.zh-CN.md, packages/varlet-ui/README.md, packages/varlet-ui/README.zh-CN.md
=> docs: rename chinese playground and remove CSDN IDE link

packages/varlet-ui/src/fab/docs/zh-CN.md
I think docs title keeps pace with example title which may be better.
=> docs(fab): docs title keeps pace with example title

packages/varlet-ui/src/button/Button.vue, packages/varlet-ui/src/button/props.ts
让加载图标的大小跟随按钮大小；目前按钮大小改变后，图标大小还是 normal，需要手动设置 loading-size
=> fix(ui/button): button loading icon size follows button

packages/varlet-ui/src/loading/docs/en-US.md, packages/varlet-ui/src/loading/docs/zh-CN.md, packages/varlet-ui/src/loading/example/index.vue
=> docs(loading): optimize docs

packages/varlet-vscode-extension/src/completions.ts
When a user enters "@", the prompt information can be correctly matched. However, when a user enters "@s", other prompt information prefixed with "@s", for example, "@select", cannot be matched. This is very unfriendly to the user in the use event prompt. I fixed the issue to make sure users get better code hints. Since hasAt and hasColon get incorrect values when the user types ":s" or "@s", I changed the way I get their values to ensure that I get the correct values in all cases.
=> fix(extension): modify prompt bug

packages/varlet-ui/src/checkbox-group/docs/en-US.md, packages/varlet-ui/src/checkbox-group/docs/zh-CN.md, packages/varlet-ui/src/checkbox-group/example/index.vue, packages/varlet-ui/src/checkbox-group/example/locale/en-US.ts, packages/varlet-ui/src/checkbox-group/example/locale/zh-CN.ts
=> docs(checkbox-group): improve docs example

packages/varlet-ui/src/bottom-navigation/BottomNavigation.vue, packages/varlet-ui/src/bottom-navigation/__tests__/__snapshots__/index.spec.js.snap, packages/varlet-ui/src/bottom-navigation/__tests__/index.spec.js, packages/varlet-ui/src/bottom-navigation/bottomNavigation.less, packages/varlet-ui/src/bottom-navigation/docs/en-US.md, packages/varlet-ui/src/bottom-navigation/docs/zh-CN.md, packages/varlet-ui/src/bottom-navigation/props.ts, packages/varlet-ui/types/bottomNavigation.d.ts
=> feat(bottom-navigation): add placeholder prop

packages/varlet-ui/src/checkbox-group/docs/en-US.md, packages/varlet-ui/src/checkbox-group/docs/zh-CN.md
=> docs(checkbox): set the parameters of the toggle function to be optional

packages/varlet-ui/src/cell/Cell.vue
=> fix(cell): add missing ripple less file import

packages/varlet-ui/src/app-bar/AppBar.vue, packages/varlet-ui/src/app-bar/__tests__/__snapshots__/index.spec.js.snap, packages/varlet-ui/src/app-bar/__tests__/index.spec.js, packages/varlet-ui/src/app-bar/docs/en-US.md, packages/varlet-ui/src/app-bar/docs/zh-CN.md, packages/varlet-ui/src/app-bar/props.ts, packages/varlet-ui/types/appBar.d.ts
=> feat(app-bar): add placeholder prop

packages/varlet-ui/src/radio/Radio.vue, packages/varlet-ui/src/radio/docs/en-US.md, packages/varlet-ui/src/radio/docs/zh-CN.md, packages/varlet-ui/types/radio.d.ts
=> feat(radio): default slot export checked

packages/varlet-ui/src/card/Card.vue, packages/varlet-ui/src/card/__tests__/__snapshots__/index.spec.js.snap, packages/varlet-ui/src/card/__tests__/index.spec.js, packages/varlet-ui/src/card/docs/en-US.md, packages/varlet-ui/src/card/docs/zh-CN.md, packages/varlet-ui/types/card.d.ts
=> feat(card): export class for title, subtitle and description slot

packages/varlet-ui/src/checkbox-group/CheckboxGroup.vue, packages/varlet-ui/src/checkbox-group/__tests__/__snapshots__/index.spec.js.snap
=> refactor(checkbox): optimized code

packages/varlet-ui/src/utils/components.ts
修复 `dialog`,`action-sheet`,`picker` 等组件在 `onClose` 和 `onConfirm` 事件中进行路由跳转导致的异常问题：
```js
Dialog({
message: "are you sure?",
confirmButtonText: "yes",
onConfirm: () => {
router.back();
},
});
```
异常信息：
```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
``` 
原因是组件内部的以下的两个事件都调用了一次 `unmountInstance` 方法，在第二次调用时 `dom` 元素已经不在 `body` 中了，所以调用 `document.body.removeChild(host)` 会报错
```js
onClosed: () => {
call(reactivePickerOptions.onClosed)
unmountInstance()
resetSingletonOptions()
},
onRouteChange: () => {
unmountInstance()
resetSingletonOptions()
}
```
[点击跳转最小复现代码](https://github.com/lzj97/varlet-demo)
复现步骤：
启动后点击 `about` …
=> fix: fix dialog unmount instance error

packages/varlet-ui/src/checkbox/Checkbox.vue, packages/varlet-ui/src/checkbox/props.ts, packages/varlet-ui/src/counter/Counter.vue, packages/varlet-ui/src/counter/docs/en-US.md, packages/varlet-ui/src/counter/docs/zh-CN.md, packages/varlet-ui/src/counter/props.ts, packages/varlet-ui/src/input/docs/en-US.md, packages/varlet-ui/src/input/docs/zh-CN.md, packages/varlet-ui/src/radio-group/RadioGroup.vue, packages/varlet-ui/src/radio-group/props.ts, packages/varlet-ui/src/radio/Radio.vue, packages/varlet-ui/src/radio/props.ts, packages/varlet-ui/src/select/docs/en-US.md, packages/varlet-ui/src/select/docs/zh-CN.md, packages/varlet-ui/src/switch/Switch.vue, packages/varlet-ui/src/switch/docs/en-US.md, packages/varlet-ui/src/switch/docs/zh-CN.md, packages/varlet-ui/src/switch/props.ts, packages/varlet-ui/src/uploader/docs/en-US.md, packages/varlet-ui/src/uploader/docs/zh-CN.md, packages/varlet-ui/types/checkbox.d.ts
=> types(ui): optimize form component validate trigger type name

packages/varlet-ui/src/card/docs/en-US.md
update card component en docs.
=> docs(card): remove useless filled prop

packages/varlet-ui/src/uploader/Uploader.vue, packages/varlet-ui/src/uploader/docs/en-US.md, packages/varlet-ui/src/uploader/docs/zh-CN.md, packages/varlet-ui/src/uploader/example/index.vue, packages/varlet-ui/src/uploader/example/locale/en-US.ts, packages/varlet-ui/src/uploader/example/locale/zh-CN.ts, packages/varlet-ui/types/uploader.d.ts
=> feat(ui/uploader): support remove button slot

packages/varlet-ui/src/uploader/__tests__/__snapshots__/index.spec.js.snap, packages/varlet-ui/src/uploader/__tests__/index.spec.js
=> test(ui/uploader): add remove button slot test case

packages/varlet-ui/docs/browserAdaptation.en-US.md, packages/varlet-ui/docs/browserAdaptation.zh-CN.md
=> docs: add github link for postcss-px-to-viewport

packages/varlet-ui/src/radio/Radio.vue
changed the tabindex back to initial proposal - which allows for left/right arrow keys navigation - the current radiogroup keyboard navigation behaviour is unpredictable and not working as inteded
=> fix(radio): changed tabindex to so nav works

packages/varlet-ui/src/collapse-item/collapseItem.less
https://github.com/user-attachments/assets/40024cde-6976-4c84-96fe-acdbecdc55c5
close #1876
=> fix(ui/collapse-item): use correct css variable to control `divider`

packages/varlet-ui/src/snackbar/docs/en-US.md
```diff
- <var-button type="warning" block @click="Snackbar('Hello, I'm a snackbar')">Basic Usage</var-button>
+ <var-button type="warning" block @click="Snackbar('Hello, I\'m a snackbar')">Basic Usage</var-button>
```
Fix english quotation conflict
=> docs: fix english quotation conflict
