varletjs/varlet

packages/varlet-touch-emulator/package.json

发现了一个小bug，导致@varlet/touch-emulator在vite下导入错误。

Bug Fix: Touch-emulator entry point

---

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/form/__tests__/index.spec.js

feat: 添加form组件单元测试

---

packages/varlet-ui/src/home/example/index.vue

change varletConfig import path from relative paths to absolute paths

change varletConfig import path

---

packages/varlet-cli/site/pc/App.vue
packages/varlet-ui/src/card/docs/en-US.md
packages/varlet-ui/src/card/example/locale/en-US.ts

docs(ui/card): 英文文档和api项样式修改

---

packages/varlet-ui/src/divider/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/divider/__tests__/index.spec.js

test(ui/divider): add test case for web
affects: @varlet/ui
add test case for web

test(ui/divider): add test case for web

---

packages/varlet-ui/src/input/Input.vue

fix:clearable input icon's bug

---

packages/varlet-ui/src/loading/docs/en-US.md
packages/varlet-ui/src/loading/docs/zh-CN.md

docs:fix bug of loading doc

---

packages/varlet-ui/src/image-preview/ImagePreview.vue

给image-preview 的关闭按钮添加了点击事件

---

packages/varlet-ui/src/image-preview/docs/zh-CN.md
packages/varlet-ui/src/image-preview/example/index.vue
packages/varlet-ui/src/image-preview/example/locale/en-US.ts
packages/varlet-ui/src/image-preview/example/locale/index.ts
packages/varlet-ui/src/image-preview/example/locale/zh-CN.ts

docs(ui/image-preview):  add example and zh-CN.md

---

packages/varlet-ui/src/checkbox/checkbox.less

- replace checkbox less vars with css vars.

refactor(ui/checkbox): replace less-vars with css-vars

---

packages/varlet-ui/src/image-preview/docs/zh-CN.md
packages/varlet-ui/src/image-preview/example/index.vue
packages/varlet-ui/src/image-preview/example/locale/en-US.ts
packages/varlet-ui/src/image-preview/example/locale/zh-CN.ts

image-preview example和中文文档规整

---

package-lock.json
packages/varlet-ui/src/image-preview/docs/en-US.md
packages/varlet-ui/varlet.config.js

docs: image-preview英文文档编写

---

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/input/Input.vue
packages/varlet-ui/src/input/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/input/input.less

fix(ui/input): fix the wrong style of input

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/1-bug-report.md
.github/ISSUE_TEMPLATE/2-feature-request.md
.github/ISSUE_TEMPLATE/3-style.md
.github/ISSUE_TEMPLATE/4-docs.md
.github/PULL_REQUEST_TEMPLATE.md

chore(config) : create some management templates

---

packages/varlet-ui/src/app-bar/docs/en-US.md

docs(ui/app-bar): ui/app-bar

---

lerna.json
packages/varlet-ui/src/uploader/Uploader.vue
packages/varlet-ui/src/uploader/__tests__/index.spec.js
packages/varlet-ui/src/uploader/docs/en-US.md
packages/varlet-ui/src/uploader/docs/zh-CN.md
packages/varlet-ui/src/uploader/example/index.vue
packages/varlet-ui/src/uploader/example/locale/en-US.ts
packages/varlet-ui/src/uploader/example/locale/zh-CN.ts
packages/varlet-ui/src/utils/shared.ts

feat(uploader): 添加onRemove条件删除

---

packages/varlet-ui/src/utils/shared.ts

perf(shared): throttle节流修改

---

packages/varlet-ui/src/row/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/row/__tests__/index.spec.js
packages/varlet-ui/src/space/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/space/__tests__/index.spec.js
packages/varlet-ui/src/space/docs/en-US.md
packages/varlet-ui/src/space/docs/zh-CN.md

refactor:adjustment unit test

---

packages/varlet-ui/src/divider/divider.less
packages/varlet-ui/src/divider/example/index.vue

…sformY,use align-items: center
affects: @varlet/ui
---
---

fix(divider): fix the offset problem when the divider is vertical

---

packages/varlet-ui/src/collapse-menu-group/CollapseMenuGroup.vue
packages/varlet-ui/src/collapse-menu-group/collapseMenuGroup.less
packages/varlet-ui/src/collapse-menu-group/example/index.vue
packages/varlet-ui/src/collapse-menu-group/example/locale/en-US.ts
packages/varlet-ui/src/collapse-menu-group/example/locale/zh-CN.ts
packages/varlet-ui/src/collapse-menu-group/props.ts

---
feat: add collapseMenuGroup
- 添加了 collapseMenuGroup 组件
- 添加了对应的样式文件
- 修改 props.ts
- 编写了 example 和对应国际化文件
---

feat: add collapseMenuGroup

---

packages/varlet-ui/src/collapse-menu-item/CollapseMenuItem.tsx
packages/varlet-ui/src/collapse-menu-item/example/index.vue

refactor(ui/collapse-menu-item): destructuring assignment from props

---

packages/varlet-cli/site/index.html
packages/varlet-cli/site/mobile.html

分享到企业微信群里的时候发现没有图片，添加下og协议指定分享小图，描述的就没有加了
---
---

chore: add og protocol

---

packages/varlet-ui/docs/ide.zh-CN.md

docs: 更新 开发工具支持 中文文档的中英文排版

---

packages/varlet-ui/docs/ide.zh-CN.md

docs(modify ide.zh): modify ide.zh文档

---

packages/varlet-ui/docs/home.en-US.md
packages/varlet-ui/src/back-top/docs/en-US.md
packages/varlet-ui/src/cell/docs/en-US.md
packages/varlet-ui/src/collapse/docs/en-US.md
packages/varlet-ui/src/countdown/docs/en-US.md
packages/varlet-ui/src/counter/docs/en-US.md
packages/varlet-ui/src/date-picker/docs/en-US.md
packages/varlet-ui/src/index-bar/docs/en-US.md
packages/varlet-ui/src/pagination/docs/en-US.md
packages/varlet-ui/src/pull-refresh/docs/en-US.md
packages/varlet-ui/src/slider/docs/en-US.md
packages/varlet-ui/src/snackbar/docs/en-US.md
packages/varlet-ui/src/steps/docs/en-US.md
packages/varlet-ui/src/switch/docs/en-US.md
packages/varlet-ui/src/time-picker/docs/en-US.md

docs(ui/counter): change article language

---

README.md

---
---
- doc: add the space between Chinese and English in Readme.md

doc: add the space between Chinese and English in Readme.md

---

README.md
packages/varlet-cli/README.md

---
---
- doc: add the space between Chinese and English in varlet/cli readme.md

doc: add the space between Chinese and English in varlet/cli readme.md

---

.github/CONTRIBUTING.md
README.en-US.md
README.md
packages/varlet-eslint-config/README.md
packages/varlet-stylelint-config/README.md
packages/varlet-ui/README.en-US.md
packages/varlet-ui/README.md
packages/varlet-ui/docs/browserAdaptation.en-US.md
packages/varlet-ui/docs/browserAdaptation.zh-CN.md
packages/varlet-ui/docs/importOnDemand.en-US.md
packages/varlet-ui/docs/importOnDemand.zh-CN.md
packages/varlet-ui/docs/openSourceGuide.en-US.md
packages/varlet-ui/docs/openSourceGuide.zh-CN.md
packages/varlet-ui/docs/quickstart.en-US.md
packages/varlet-ui/docs/quickstart.zh-CN.md

docs: update pnpm

---

packages/varlet-ui/src/menu/Menu.tsx

refactor(ui): menu component style use computed && modify calc type

---

packages/varlet-ui/src/icon/docs/zh-CN.md

docs: modify punctuation

---

packages/varlet-ui/src/cell/docs/zh-CN.md

docs: add the space between Chinese and English in varlet-ui

---

packages/varlet-ui/src/button/docs/zh-CN.md

docs(ui): fix docs typo

---

packages/varlet-ui/src/locale/index.ts

change useLocale type to generic
---
---

chore(types/ui): change useLocale type to generic

---

packages/varlet-ui/src/button/Button.vue
packages/varlet-ui/src/button/docs/en-US.md
packages/varlet-ui/src/button/docs/zh-CN.md
packages/varlet-ui/src/button/example/index.vue
packages/varlet-ui/src/button/example/locale/en-US.ts
packages/varlet-ui/src/button/example/locale/zh-CN.ts
packages/varlet-ui/src/button/props.ts
packages/varlet-ui/src/utils/shared.ts

Feat(button): add auto-loading prop

---

packages/varlet-cli/package.json
packages/varlet-cli/src/commands/gen.ts
packages/varlet-cli/src/commands/release.ts
packages/varlet-cli/src/module.d.ts
pnpm-lock.yaml

feat: release version support customization

---

packages/varlet-ui/src/space/Space.tsx

perf(ui/spaces): add class

---

packages/varlet-ui/src/picker/Picker.vue

perf(ui/Picker): add class

---

packages/varlet-ui/src/list/List.vue

perf(ui/list): add class and call function

---

packages/varlet-ui/src/form/Form.vue
packages/varlet-ui/src/input/Input.vue
packages/varlet-ui/src/select/Select.vue

perf(ui/select): add class and call function

---

packages/varlet-ui/src/snackbar/core.vue

perf(ui/snackbar): add class
perf(ui/snackbar): add class
---
---

perf(ui/snackbar): add class

---

packages/varlet-ui/src/col/Col.vue

perf(ui/col): add class

---

packages/varlet-ui/src/row/Row.vue

perf(ui/row): add class

---

packages/varlet-ui/src/sticky/Sticky.vue

perf(ui/sticky): add class and call

---

packages/varlet-ui/src/swipe/Swipe.vue

perf(ui/swipe): add class and call

---

packages/varlet-ui/src/list/List.vue
packages/varlet-ui/src/uploader/docs/zh-CN.md

docs(ui/uploader): fix space

---

packages/varlet-ui/src/lazy/index.ts
packages/varlet-ui/src/ripple/index.ts
packages/varlet-ui/src/table/Table.vue
packages/varlet-ui/src/tabs-items/TabsItems.vue
packages/varlet-ui/src/tabs/Tabs.vue

perf: Modify the class display method in table, tabs, ripple and lazy

---

packages/varlet-ui/src/tabs/docs/zh-CN.md

docs(ui/tabs): fix space

---

packages/varlet-ui/src/dialog/Dialog.vue

perf(ui/dialog): add class and call

---

packages/varlet-ui/src/tab-item/TabItem.vue

---
- [x ] Fix linting errors
- [x ] Tests have been added / updated (or snapshots)
---
Add class to tab-item component

perf(ui/tab-item): add class

---

packages/varlet-ui/src/rate/docs/zh-CN.md
packages/varlet-ui/src/slider/docs/zh-CN.md

docs(ui/rate&slider): fix space

---

packages/varlet-ui/src/list/docs/en-US.md
packages/varlet-ui/src/list/docs/zh-CN.md
packages/varlet-ui/src/list/example/index.vue

docs(ui/list): use the `setup script` for exmple

---

packages/varlet-ui/src/counter/docs/en-US.md
packages/varlet-ui/src/counter/docs/zh-CN.md
packages/varlet-ui/src/counter/example/index.vue

docs(ui/counter): use the setup script for exmple and docs

---

packages/varlet-ui/src/swipe/docs/en-US.md
packages/varlet-ui/src/swipe/docs/zh-CN.md
packages/varlet-ui/src/swipe/example/index.vue

docs(ui/swiper): use the `setup script` for example and docs

---

packages/varlet-ui/src/lazy/docs/en-US.md
packages/varlet-ui/src/lazy/docs/zh-CN.md
packages/varlet-ui/src/lazy/example/index.vue

docs(ui/steps): use the setup script for example and docs 

---

packages/varlet-ui/src/steps/docs/en-US.md
packages/varlet-ui/src/steps/docs/zh-CN.md
packages/varlet-ui/src/steps/example/index.vue

docs(ui/steps): use the setup script for exmple and docs

---

packages/varlet-ui/src/snackbar/docs/en-US.md
packages/varlet-ui/src/snackbar/docs/zh-CN.md
packages/varlet-ui/src/snackbar/example/index.vue

docs(ui/snackbar): use the setup script for example and docs

---

packages/varlet-ui/src/table/docs/en-US.md
packages/varlet-ui/src/table/docs/zh-CN.md
packages/varlet-ui/src/table/example/Basic.vue
packages/varlet-ui/src/table/example/FooterSlots.vue
packages/varlet-ui/src/table/example/index.vue

docs(ui/table): use the setup script for exmple and docs

---

packages/varlet-ui/src/action-sheet/docs/en-US.md
packages/varlet-ui/src/action-sheet/docs/zh-CN.md
packages/varlet-ui/src/action-sheet/example/index.vue

docs(ui/action-sheet): use the setup script for example and docs

---

packages/varlet-ui/src/picker/docs/en-US.md
packages/varlet-ui/src/picker/docs/zh-CN.md
packages/varlet-ui/src/picker/example/index.vue

docs(ui/picker): use the setup script for exmple and docs

---

packages/varlet-ui/src/image-preview/docs/en-US.md
packages/varlet-ui/src/image-preview/docs/zh-CN.md
packages/varlet-ui/src/image-preview/example/index.vue

docs(ui/image-preview): use the setup script for exmple and docs

---

packages/varlet-ui/src/icon/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/icon/docs/en-US.md
packages/varlet-ui/src/icon/docs/zh-CN.md
packages/varlet-ui/src/icon/example/index.vue

docs(ui/icon): use the setup script for example and docs, update snapshot

---

packages/varlet-ui/src/cell/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/cell/docs/en-US.md
packages/varlet-ui/src/cell/docs/zh-CN.md
packages/varlet-ui/src/cell/example/index.vue

docs(ui/cell): use the setup script for example and docs,  update snapshot

---

packages/varlet-ui/src/back-top/docs/en-US.md
packages/varlet-ui/src/back-top/docs/zh-CN.md
packages/varlet-ui/src/back-top/example/index.vue

docs(back-top): format doc

---

packages/varlet-ui/src/pull-refresh/docs/en-US.md
packages/varlet-ui/src/pull-refresh/docs/zh-CN.md
packages/varlet-ui/src/pull-refresh/example/index.vue

docs(pull-refresh): format doc

---

packages/varlet-ui/src/image/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/image/docs/en-US.md
packages/varlet-ui/src/image/docs/zh-CN.md
packages/varlet-ui/src/image/example/index.vue

docs(ui/image): use the setup script for example and docs, update the snap

---

packages/varlet-ui/src/select/docs/en-US.md
packages/varlet-ui/src/select/docs/zh-CN.md
packages/varlet-ui/src/select/example/index.vue

docs(ui/select): use the setup script for exmple and docs

---

packages/varlet-ui/src/menu/docs/en-US.md
packages/varlet-ui/src/menu/docs/zh-CN.md
packages/varlet-ui/src/menu/example/index.vue

docs(menu): format doc

---

packages/varlet-ui/src/popup/docs/en-US.md
packages/varlet-ui/src/popup/docs/zh-CN.md
packages/varlet-ui/src/popup/example/index.vue

docs(popup): format doc

---

packages/varlet-ui/src/date-picker/docs/en-US.md
packages/varlet-ui/src/date-picker/docs/zh-CN.md
packages/varlet-ui/src/date-picker/example/index.vue

docs(ui/data-picker): use the setup script for exmple and docs

---

packages/varlet-ui/src/time-picker/docs/en-US.md
packages/varlet-ui/src/time-picker/docs/zh-CN.md
packages/varlet-ui/src/time-picker/example/index.vue

docs(ui/time-picker): use the setup script for exmple and docs

---

packages/varlet-ui/src/countdown/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/countdown/docs/en-US.md
packages/varlet-ui/src/countdown/docs/zh-CN.md
packages/varlet-ui/src/countdown/example/index.vue

docs(ui/countdown): use the setup script for example and docs

---

packages/varlet-cli/src/compiler/compileSiteEntry.ts
packages/varlet-cli/src/shared/fsUtils.ts

refactor(cli/compileSiteEntry): use glob replace regexp to find component path

---

packages/varlet-ui/src/tabs/docs/en-US.md
packages/varlet-ui/src/tabs/docs/zh-CN.md
packages/varlet-ui/src/tabs/example/index.vue

docs(ui/tabs): use the setup script for exmple and docs

---

packages/varlet-ui/src/index-bar/docs/en-US.md
packages/varlet-ui/src/index-bar/docs/zh-CN.md
packages/varlet-ui/src/index-bar/example/index.vue

docs(ui/index-bar): use the setup script for exmple and docs

---

packages/varlet-ui/src/loading/docs/en-US.md
packages/varlet-ui/src/loading/docs/zh-CN.md

close [#485](https://github.com/varletjs/varlet/issues/485)

docs(loading): Update this loading component docs.

---

packages/varlet-ui/src/image/__tests__/index.spec.js

test(image): Update this image component unit test

---

packages/varlet-ui/src/badge/docs/en-US.md
packages/varlet-ui/src/badge/docs/zh-CN.md

close [#494](https://github.com/varletjs/varlet/issues/494)

docs(badge): Update this badge component docs.

---

packages/varlet-ui/src/badge/__tests__/index.spec.js

close [#492](https://github.com/varletjs/varlet/issues/492)

test(badge): Update this badge component unit test

---

packages/varlet-ui/docs/importOnDemand.zh-CN.md
packages/varlet-ui/docs/openSourceGuide.zh-CN.md
packages/varlet-ui/docs/quickstart.zh-CN.md
packages/varlet-ui/src/themes/docs/zh-CN.md

All changes are only for docs.
[refer](https://github.com/varletjs/varlet/projects/4#card-74336815)

docs(cn): add logical space between normal text and code wrap

---

packages/varlet-ui/src/steps/docs/en-US.md
packages/varlet-ui/src/steps/docs/zh-CN.md

fix: docs(ui/steps): use the setup script for exmple and docs

---

packages/varlet-ui/src/button/docs/en-US.md
packages/varlet-ui/src/divider/docs/en-US.md
packages/varlet-ui/src/pagination/docs/en-US.md

docs(ui/button): use the setup script for exmple and docs

---

packages/varlet-ui/src/picker/picker.less
packages/varlet-ui/src/themes/dark/picker.ts

fix(ui/picker): add picker missing style

---

packages/varlet-ui/src/sticky/__tests__/index.spec.js

close [#515](https://github.com/varletjs/varlet/issues/515)

test(sticky): Update this sticky component unit test.

---

packages/varlet-ui/src/picker/Picker.vue
packages/varlet-ui/src/picker/__tests__/component.spec.js
packages/varlet-ui/src/picker/__tests__/index.spec.js
packages/varlet-ui/src/picker/docs/en-US.md
packages/varlet-ui/src/picker/docs/zh-CN.md
packages/varlet-ui/src/picker/example/index.vue
packages/varlet-ui/src/picker/example/locale/en-US.ts
packages/varlet-ui/src/picker/example/locale/zh-CN.ts
packages/varlet-ui/src/picker/index.ts
packages/varlet-ui/src/picker/props.ts
packages/varlet-ui/types/picker.d.ts

feat(ui/picker): add props textFormatter

---

packages/varlet-cli/site/pc/App.vue
packages/varlet-cli/site/pc/components/AnimationBox.vue
packages/varlet-cli/site/pc/components/LogoAnimation.vue
packages/varlet-cli/site/pc/pages/index/index.less
packages/varlet-cli/site/pc/pages/index/index.vue

refactor(site): optimize home page style && fix the logo blink

---

packages/varlet-cli/site/pc/components/LogoAnimation.vue
packages/varlet-cli/site/pc/pages/index/index.less
packages/varlet-cli/site/pc/pages/index/index.vue

chore: make up the resize observer && homepage style

---

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/rate/example/index.vue
packages/varlet-ui/src/switch/Switch.vue
packages/varlet-ui/src/switch/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/switch/docs/en-US.md
packages/varlet-ui/src/switch/docs/zh-CN.md
packages/varlet-ui/src/switch/example/index.vue
packages/varlet-ui/src/switch/props.ts
packages/varlet-ui/src/switch/switch.less
packages/varlet-ui/src/utils/elements.ts

fix(switch): support dimension units

---

packages/varlet-cli/package.json
pnpm-lock.yaml

chore: add the `@types/glob` into `devDependencies`

---

packages/varlet-cli/generators/base/varlet.config.js
packages/varlet-cli/site/pc/components/AppHeader.vue
packages/varlet-cli/varlet.default.config.js
packages/varlet-ui/docs/cli.en-US.md
packages/varlet-ui/docs/cli.zh-CN.md
packages/varlet-ui/varlet.config.js

feat: varlet/cli site version config

---

packages/varlet-cli/site/pc/pages/index/index.less

chore(cli/site):  logo z-index

---

.github/CONTRIBUTING.md

chore: fix the typo

---

packages/varlet-cli/site/pc/components/AnimationBox.vue
packages/varlet-cli/site/pc/components/LogoAnimation.vue

fix: animationBox is not in the DomTree. the logo will not show

---

packages/varlet-ui/types/switch.d.ts

types(ui/switch): add BasicAttributes

---

packages/varlet-ui/types/tab.d.ts
packages/varlet-ui/types/tabItem.d.ts

types(ui/tab): add BasicAttributes

---

packages/varlet-ui/types/uploader.d.ts

types(ui/uploader): add BasicAttributes

---

packages/varlet-ui/types/timePicker.d.ts

types(ui/timePicker): add BasicAttributes

---

packages/varlet-ui/types/tabs.d.ts
packages/varlet-ui/types/tabsItems.d.ts

types(ui/tabs): add BasicAttributes

---

packages/varlet-ui/types/table.d.ts

types(ui/table): add BasicAttributes

---

packages/varlet-ui/types/select.d.ts

types(ui/select): add BasicAttributes

---

packages/varlet-ui/types/skeleton.d.ts

types(ui/skeleton): add BasicAttributes

---

packages/varlet-ui/types/slider.d.ts

types(ui/slider): add BasicAttributes

---

packages/varlet-ui/types/snackbar.d.ts

types(ui/snackbar): add BasicAttributes

---

packages/varlet-ui/types/space.d.ts

types(ui/space): add BasicAttributes

---

packages/varlet-ui/types/step.d.ts
packages/varlet-ui/types/steps.d.ts

types(ui/step): add BasicAttributes

---

packages/varlet-ui/types/sticky.d.ts

types(ui/sticky): add BasicAttributes

---

packages/varlet-ui/types/styleProvider.d.ts

types(ui/styleProvider): add BasicAttributes

---

packages/varlet-ui/types/progress.d.ts

types(ui/progress): add BasicAttributes

---

packages/varlet-ui/types/pullRefresh.d.ts

types(ui/pullRefresh): add BasicAttributes

---

packages/varlet-ui/types/radio.d.ts
packages/varlet-ui/types/radioGroup.d.ts

types(ui/radio): add BasicAttributes 

---

packages/varlet-ui/types/row.d.ts

types(ui/row): add BasicAttributes

---

CHANGELOG.md
package.json
packages/varlet-cli/package.json
packages/varlet-eslint-config/package.json
packages/varlet-icons/package.json
packages/varlet-markdown-vite-plugin/package.json
packages/varlet-shared/package.json
packages/varlet-stylelint-config/package.json
packages/varlet-touch-emulator/package.json
packages/varlet-ui-playground/package.json
packages/varlet-ui-playground/src/download/download.ts
packages/varlet-ui-playground/src/store.ts
packages/varlet-ui/package.json
packages/varlet-vscode-extension/package.json

---
Solve the problem that the component library must be manually introduced into the playground user code editing area
---

chore(playground): Solve the problem that the component library must be manually introduced into the playground user code editing area

---

packages/varlet-ui/docs/cli.en-US.md
packages/varlet-ui/docs/cli.zh-CN.md

docs(cli): make up the `pages` folder docs and `SitePC` configuration

---

packages/varlet-cli/site/pc/components/AnimationBox.vue
packages/varlet-cli/site/pc/components/AppHeader.vue
packages/varlet-cli/site/pc/components/LogoAnimation.vue
packages/varlet-cli/site/pc/floating.ts
packages/varlet-cli/site/pc/pages/index/index.less

refactor: refactor the animationBox and floating proxy, optimize style

---

packages/varlet-cli/lib/index.js
packages/varlet-cli/src/commands/gen.ts
packages/varlet-cli/src/index.ts
packages/varlet-cli/template/generators/base/.gitignore

chore(cli): Optimize gen commands to support imperative, interactive

---

packages/varlet-ui/src/menu/docs/en-US.md
packages/varlet-ui/src/menu/docs/zh-CN.md
packages/varlet-ui/src/menu/example/index.vue
packages/varlet-ui/src/menu/example/locale/en-US.ts
packages/varlet-ui/src/menu/example/locale/index.ts
packages/varlet-ui/src/menu/example/locale/zh-CN.ts

docs(ui/menu): update information of menu in the ui/menu scope
---
---

docs: update information of menu

---

packages/varlet-ui/types/actionSheet.d.ts

---
- [ types ] actionSheet组件下的类型变为可选
---

types(ui/actionSheet): modify some properties to be optional

---

packages/varlet-ui/docs/migrationGuide.zh-CN.md

docs: improve the new component style document

---

packages/varlet-cli/template/generators/config/default/sfc/src/button/docs/zh-CN.md
packages/varlet-cli/template/generators/config/default/tsx/src/button/docs/zh-CN.md
packages/varlet-cli/template/generators/config/i18n/sfc/src/button/Button.vue
packages/varlet-cli/template/generators/config/i18n/sfc/src/button/docs/zh-CN.md
packages/varlet-cli/template/generators/config/i18n/tsx/src/button/Button.tsx
packages/varlet-cli/template/generators/config/i18n/tsx/src/button/docs/zh-CN.md

chore(gen): cli gen revise the copy

---

packages/varlet-ui/src/dialog/Dialog.vue
packages/varlet-ui/src/dialog/example/index.vue
packages/varlet-ui/src/dialog/props.ts

add dialogWidth props to Dialog
```
Dialog({
message: pack.value.message,
dialogWidth: 220,
})
<var-dialog
..... 
dialog-width="220"
/>
```
---

feat(ui/dialog): add dialogWidth props

---

packages/varlet-ui/src/divider/Divider.vue
packages/varlet-ui/src/divider/__tests__/index.spec.js
packages/varlet-ui/src/divider/divider.less
packages/varlet-ui/src/divider/docs/en-US.md
packages/varlet-ui/src/divider/docs/zh-CN.md
packages/varlet-ui/src/divider/example/index.vue
packages/varlet-ui/src/divider/example/locale/en-US.ts
packages/varlet-ui/src/divider/example/locale/zh-CN.ts
packages/varlet-ui/src/divider/props.ts

feat(ui/divider): add hairline divider

---

.gitignore
package.json
packages/varlet-cli/src/commands/lint.ts
pnpm-lock.yaml
scripts/bootstrap.mjs
scripts/publish.mjs

---
---
add prettier 、stylelint、eslint cache

chore(cli/lint): add lint cache

---

packages/varlet-ui/src/select/Select.vue
packages/varlet-ui/src/select/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/select/docs/en-US.md
packages/varlet-ui/src/select/docs/zh-CN.md
packages/varlet-ui/src/select/example/index.vue
packages/varlet-ui/types/select.d.ts

feat(ui/select): support suffix-icon

---

packages/varlet-cli/README.en-US.md
packages/varlet-cli/README.md

---
修正 varlet-cli 中 README 文件下404链接
---

docs: fix 404 links

---

packages/varlet-cli/site/pc/components/AnimationBox.vue
packages/varlet-cli/site/pc/components/LogoAnimation.vue
packages/varlet-cli/site/pc/floating.ts

fix: some unusual behavior of LOGO animation

---

packages/varlet-ui/src/image/docs/en-US.md
packages/varlet-ui/src/image/docs/zh-CN.md

docs(ui/image): add another import method for image src

---

packages/varlet-ui/src/floating-actions-button/FloatingActionsButton.vue
packages/varlet-ui/src/floating-actions-button/floatingActionsButton.less

refactor(ui/fab): rewrite fab style and class

---

packages/varlet-ui/src/floating-actions-button/FloatingActionsButton.vue
packages/varlet-ui/src/floating-actions-button/floatingActionsButton.less

refactor(ui/fab): rewrit fab behavior

---

README.md
README.zh-CN.md
preview.yml

---
---
Add Cloud IDE preview link to view code and run varlet-ui online.

docs: add Cloud IDE preview link

---

packages/varlet-ui/src/space/Space.tsx
packages/varlet-ui/src/space/__tests__/index.spec.js
packages/varlet-ui/src/space/context.ts
packages/varlet-ui/src/space/index.ts

Support plugin options for size

feat(ui/space): support plugin options for size

---

packages/varlet-ui/src/breadcrumb/Breadcrumb.vue
packages/varlet-ui/src/breadcrumb/breadcrumb.less
packages/varlet-ui/src/breadcrumb/props.ts
packages/varlet-ui/src/breadcrumbs/breadcrumbs.less
packages/varlet-ui/src/breadcrumbs/docs/en-US.md
packages/varlet-ui/src/breadcrumbs/docs/zh-CN.md
packages/varlet-ui/src/breadcrumbs/example/index.vue
packages/varlet-ui/src/breadcrumbs/example/locale/en-US.ts
packages/varlet-ui/src/breadcrumbs/example/locale/zh-CN.ts

perf(ui/breadcrumb): optimize docs

---

packages/varlet-ui/src/form/Form.vue
packages/varlet-ui/src/form/docs/en-US.md
packages/varlet-ui/src/form/docs/zh-CN.md
packages/varlet-ui/src/form/example/index.vue
packages/varlet-ui/src/form/props.ts
packages/varlet-ui/src/form/provide.ts
packages/varlet-ui/types/form.d.ts

---
form support scroll to first error
---

feat(ui/form): support scroll to first error

---

packages/varlet-ui/src/counter/docs/en-US.md
packages/varlet-ui/src/counter/docs/zh-CN.md
packages/varlet-ui/src/counter/example/index.vue

docs(ui/counter): change arrow into function at setup

---

packages/varlet-ui/src/action-sheet/docs/en-US.md
packages/varlet-ui/src/action-sheet/docs/zh-CN.md
packages/varlet-ui/src/action-sheet/example/index.vue
packages/varlet-ui/src/action-sheet/example/locale/index.ts

docs(ui/action-sheet): optimize docs

---

packages/varlet-ui/src/pull-refresh/PullRefresh.vue

fix(ui/pull-refresh): fix pull-refresh touchMove

---

packages/varlet-ui/src/input/Input.vue
packages/varlet-ui/src/input/example/index.vue
packages/varlet-ui/src/input/example/locale/en-US.ts
packages/varlet-ui/src/input/example/locale/zh-CN.ts
packages/varlet-ui/src/input/input.less
packages/varlet-ui/src/input/props.ts

feat(ui/input): support outlined input

---

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/input/Input.vue
packages/varlet-ui/src/input/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/input/input.less
packages/varlet-ui/src/pagination/__tests__/__snapshots__/index.spec.js.snap

---
适配了下真机，动画按照微信上说得改了，手动测试了下，应该没啥问题了。可以再看下，有问题再沟通我 
---

refactor(ui/input): adaptation real mobile

---

packages/varlet-ui/src/card/Card.vue

types(ui/card): fix position type

---

packages/varlet-ui/src/chip/Chip.vue
packages/varlet-ui/src/col/Col.vue
packages/varlet-ui/src/image/Image.vue
packages/varlet-ui/src/row/Row.vue

chore: explicitly invoke event listeners

---

packages/varlet-cli/README.md
packages/varlet-cli/README.zh-CN.md
packages/varlet-cli/site/pc/Layout.vue
packages/varlet-cli/site/utils.ts
packages/varlet-ui/docs/cli.en-US.md
packages/varlet-ui/docs/cli.zh-CN.md

feat: add useRouteMobile in cli/site/pc/Layout

---

packages/varlet-ui/src/button-group/docs/en-US.md
packages/varlet-ui/src/button-group/docs/zh-CN.md
packages/varlet-ui/src/button/docs/en-US.md
packages/varlet-ui/src/button/docs/zh-CN.md
packages/varlet-ui/src/card/docs/en-US.md
packages/varlet-ui/src/card/docs/zh-CN.md
packages/varlet-ui/types/buttonGroup.d.ts

docs: md format

---

packages/varlet-ui/src/button/Button.vue
packages/varlet-ui/src/button/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/button/button.less
packages/varlet-ui/src/checkbox-group/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/date-picker/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/picker/__tests__/__snapshots__/component.spec.js.snap
packages/varlet-ui/src/snackbar/__tests__/__snapshots__/component.spec.js.snap
packages/varlet-ui/src/uploader/__tests__/__snapshots__/index.spec.js.snap

feat(button): 为button按钮实现hover效果

---

packages/varlet-ui/src/swipe-item/provide.ts
packages/varlet-ui/src/swipe/provide.ts

refactor(ui/swipe): refactor from @varlet/use

---

packages/varlet-ui/src/step/provide.ts
packages/varlet-ui/src/steps/provide.ts

refactor(ui/steps): refactor from @varlet/use

---

packages/varlet-ui/src/index-anchor/provide.ts
packages/varlet-ui/src/index-bar/provide.ts

refactor(ui/index-bar): refactor from @varlet/use

---

packages/varlet-ui/src/bottom-navigation-item/provide.ts
packages/varlet-ui/src/bottom-navigation/provide.ts

refactor(ui/bottom-navigation): refactor from @varlet/use

---

packages/varlet-ui/src/fab/example/locale/en-US.ts

docs(ui/fab): big words

---

packages/varlet-ui/src/fab/example/locale/en-US.ts
packages/varlet-ui/src/image-preview/__tests__/index.spec.js
packages/varlet-ui/src/image-preview/docs/en-US.md
packages/varlet-ui/src/image-preview/docs/zh-CN.md
packages/varlet-ui/src/image-preview/index.ts
packages/varlet-ui/types/imagePreview.d.ts

feat(ui/image-preview): add setDefaultOptions and resetDefaultOptions

---

packages/varlet-ui/src/bottom-navigation/docs/en-US.md
packages/varlet-ui/src/bottom-navigation/docs/zh-CN.md

docs: button navigation  modify the  link in the document

---

packages/varlet-ui/src/app-bar/AppBar.vue
packages/varlet-ui/src/app-bar/docs/en-US.md
packages/varlet-ui/src/app-bar/docs/zh-CN.md
packages/varlet-ui/src/app-bar/props.ts
packages/varlet-ui/src/table/Table.vue
packages/varlet-ui/src/table/docs/en-US.md
packages/varlet-ui/src/table/docs/zh-CN.md
packages/varlet-ui/src/table/props.ts
packages/varlet-ui/src/tabs/Tabs.vue
packages/varlet-ui/src/tabs/docs/en-US.md
packages/varlet-ui/src/tabs/docs/zh-CN.md
packages/varlet-ui/src/tabs/props.ts
packages/varlet-ui/types/appBar.d.ts
packages/varlet-ui/types/table.d.ts
packages/varlet-ui/types/tabs.d.ts

feat: suppert elevation for Table、Tabs、AppBar

---

packages/varlet-ui/src/counter/Counter.vue
packages/varlet-ui/src/counter/docs/en-US.md
packages/varlet-ui/src/counter/docs/zh-CN.md
packages/varlet-ui/src/counter/props.ts
packages/varlet-ui/src/uploader/Uploader.vue
packages/varlet-ui/src/uploader/docs/en-US.md
packages/varlet-ui/src/uploader/docs/zh-CN.md
packages/varlet-ui/src/uploader/props.ts
packages/varlet-ui/types/counter.d.ts
packages/varlet-ui/types/uploader.d.ts

feat(ui/uploader|counter): support elevation

---

packages/varlet-ui/types/pagination.d.ts

fix(pagination): fix pagination not required props

---

packages/varlet-ui/src/divider/__tests__/index.spec.js

---
---
close issues #964 
Before:
Now

test(divider): Improve component test coverage

---

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/form/__tests__/index.spec.js
packages/varlet-ui/src/slider/Slider.vue
packages/varlet-ui/src/slider/__tests__/index.spec.js
packages/varlet-ui/src/slider/docs/en-US.md
packages/varlet-ui/src/slider/docs/zh-CN.md
packages/varlet-ui/src/slider/example/index.vue
packages/varlet-ui/src/slider/example/locale/en-US.ts
packages/varlet-ui/src/slider/example/locale/zh-CN.ts
packages/varlet-ui/src/slider/props.ts
packages/varlet-ui/src/slider/slider.less
packages/varlet-ui/src/utils/elements.ts
packages/varlet-ui/types/slider.d.ts

使 slider 组件支持 'vertical' 模式。修改点主要有：
+ 对样式区分 `horizontal` 和 `vertical` 前缀
+ 调整鼠标移动距离的计算方式，支持y轴
#985 
---
---

feat(slider): support vertical mode

---

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/form/__tests__/index.spec.js
packages/varlet-ui/src/slider/Slider.vue
packages/varlet-ui/src/slider/__tests__/index.spec.js
packages/varlet-ui/src/slider/docs/en-US.md
packages/varlet-ui/src/slider/docs/zh-CN.md
packages/varlet-ui/src/slider/example/index.vue
packages/varlet-ui/src/slider/slider.less

+ 修复样式类名不规范
+ 气泡label边距
+ 示例调整
---
---

fix(ui/slider): optimize slider style and classes

---

packages/varlet-ui/src/uploader/Uploader.vue
packages/varlet-ui/src/uploader/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/uploader/__tests__/index.spec.js
packages/varlet-ui/src/uploader/docs/en-US.md
packages/varlet-ui/src/uploader/docs/zh-CN.md
packages/varlet-ui/src/uploader/example/index.vue
packages/varlet-ui/src/uploader/example/locale/en-US.ts
packages/varlet-ui/src/uploader/example/locale/zh-CN.ts
packages/varlet-ui/src/uploader/props.ts
packages/varlet-ui/src/uploader/uploader.less
packages/varlet-ui/types/uploader.d.ts

feat(ui-uploader): uploader进度条功能重新pr   （单测报错了，需要耗子支援~~~）

---

packages/varlet-ui/src/input/Input.vue
packages/varlet-ui/src/input/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/input/__tests__/index.spec.js
packages/varlet-ui/src/input/docs/en-US.md
packages/varlet-ui/src/input/docs/zh-CN.md
packages/varlet-ui/src/input/props.ts
packages/varlet-ui/types/input.d.ts

feat(ui/input): support enterkeyhint for Input

---

packages/varlet-ui/src/form/__tests__/index.spec.js
packages/varlet-ui/src/slider/Slider.vue
packages/varlet-ui/src/slider/__tests__/index.spec.js
packages/varlet-ui/src/slider/slider.less

fix #1008 
1. 参考 swipe 修复默认滚动行为
2. 垂直模式时左右外边距调整为上下外边距，避免检验信息过近
---
---

fix(ui/slider): 修复滑块拖动时屏幕滚动

---

packages/varlet-ui/src/field-decorator/fieldDecorator.less

fix(ui/fieldDecorator): placeholder width exceeds container size

---

packages/varlet-ui/src/field-decorator/FieldDecorator.vue
packages/varlet-ui/src/field-decorator/fieldDecorator.less
packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/input/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/pagination/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/select/__tests__/__snapshots__/index.spec.js.snap

refactor(ui/fieldDecorator): refactoring placeholder animation

---

packages/varlet-ui/src/card/Card.vue
packages/varlet-ui/src/menu/usePopover.ts
packages/varlet-ui/src/ripple/index.ts

ripple ：Modify the field #1023

---

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/slider/Slider.vue
packages/varlet-ui/src/slider/__tests__/index.spec.js
packages/varlet-ui/src/slider/slider.less

fix(ui/slider): fix the style of validation fails

---

packages/varlet-ui/src/radio-group/docs/en-US.md
packages/varlet-ui/src/radio-group/docs/zh-CN.md
packages/varlet-ui/src/radio-group/example/index.vue
packages/varlet-ui/src/radio-group/example/locale/en-US.ts
packages/varlet-ui/src/radio-group/example/locale/zh-CN.ts

docs(radio group): added vertical direction document

---

packages/varlet-ui/src/picker/Picker.vue
packages/varlet-ui/src/picker/__tests__/component.spec.js

feat: ios级联不能点击问题修复

---

packages/varlet-ui/src/picker/Picker.vue
packages/varlet-ui/src/picker/__tests__/component.spec.js

feat(ui-picker): Change to click event

---

packages/varlet-ui/src/progress/Progress.vue

feat(ui-progress): Optimized code

---

packages/varlet-ui/src/list/__tests__/index.spec.js
packages/varlet-ui/src/tab-item/TabItem.vue
packages/varlet-ui/src/tab-item/provide.ts
packages/varlet-ui/src/tabs-items/TabsItems.vue
packages/varlet-ui/src/tabs-items/provide.ts

fix(ui): Fixed the Tab-item height bug

---

packages/varlet-vscode-extension/src/commands.ts
packages/varlet-vscode-extension/src/constant.ts

chore: Update vscode  extension button link address

---

packages/varlet-ui/src/pull-refresh/PullRefresh.vue
packages/varlet-ui/src/slider/Slider.vue
packages/varlet-ui/src/sticky/Sticky.vue
packages/varlet-ui/src/time-picker/TimePicker.vue
packages/varlet-ui/src/time-picker/clock.vue

feat(ui): replace getBoundingClientRect with getRect

---

packages/varlet-ui/src/image/Image.vue
packages/varlet-ui/src/image/__tests__/index.spec.js
packages/varlet-ui/src/image/docs/en-US.md
packages/varlet-ui/src/image/docs/zh-CN.md
packages/varlet-ui/src/image/example/index.vue
packages/varlet-ui/src/image/example/locale/en-US.ts
packages/varlet-ui/src/image/example/locale/zh-CN.ts
packages/varlet-ui/src/image/props.ts
packages/varlet-ui/types/image.d.ts

feat(ui/image): add error slot

---

packages/varlet-vscode-extension/src/completions.ts

---
---
before:
https://github.com/varletjs/varlet/assets/49502875/f6d61001-3c59-499a-b221-1c9876bb72f7
now: 
https://github.com/varletjs/varlet/assets/49502875/80a38f32-353b-4390-b75c-fde3fcc79583
fix #1063

feat(extension): Filter component fill prompt when entering information inside an element

---

packages/varlet-cli/src/node/config/varlet.default.config.ts

---
update default config desc
---

chore: update default config desc

---

packages/varlet-ui/src/field-decorator/FieldDecorator.vue
packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/input/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/pagination/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/select/__tests__/__snapshots__/index.spec.js.snap

---
---
修复 placeholder 为动态的时候会出现样式问题
[playground](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFZhcmxldCEnKVxuY29uc3QgcGxhY2Vob2xkZXIgPSByZWYoXCJcIilcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgc3R5bGU9XCJoZWlnaHQ6MjBweFwiIC8+XG4gIDx2YXItaW5wdXQgOnBsYWNlaG9sZGVyPVwicGxhY2Vob2xkZXJcIiB2LW1vZGVsPVwibXNnXCIgdmFyaWFudD1cIm91dGxpbmVkXCIgLz5cbiAgPHZhci1pbnB1dCBwbGFjZWhvbGRlcj1cIuivt+i+k+WFpVwiIHYtbW9kZWw9XCJwbGFjZWhvbGRlclwiIC8+XG48L3RlbXBsYXRlPlxuIiwiUGxheWdyb3VuZC52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAg …

fix(ui/fieldDecorator): fix style error when placeholder is empty

---

packages/varlet-ui/src/pagination/pagination.less

fix: fix a style bug in varlet-ui/Pagination/pagination.less

---

packages/varlet-ui/src/step/Step.vue
packages/varlet-ui/src/step/step.less
packages/varlet-ui/src/steps/Steps.vue
packages/varlet-ui/src/steps/docs/en-US.md
packages/varlet-ui/src/steps/docs/zh-CN.md
packages/varlet-ui/src/steps/example/index.vue
packages/varlet-ui/src/steps/provide.ts

fix(steps): reimplement the connection line style

---

packages/varlet-ui/src/rate/Rate.vue
packages/varlet-ui/src/rate/__tests__/index.spec.js
packages/varlet-ui/src/rate/docs/en-US.md
packages/varlet-ui/src/rate/docs/zh-CN.md
packages/varlet-ui/src/rate/example/index.vue
packages/varlet-ui/src/rate/example/locale/en-US.ts
packages/varlet-ui/src/rate/example/locale/zh-CN.ts
packages/varlet-ui/src/rate/props.ts
packages/varlet-ui/types/rate.d.ts

feat(ui/rate): allow to clear score

---

packages/varlet-ui/src/button/button.less
packages/varlet-ui/src/button/docs/en-US.md
packages/varlet-ui/src/button/docs/zh-CN.md
packages/varlet-ui/src/link/docs/en-US.md
packages/varlet-ui/src/link/docs/zh-CN.md
packages/varlet-ui/src/link/link.less
packages/varlet-ui/src/themes/dark/button.ts
packages/varlet-ui/src/themes/dark/index.ts
packages/varlet-ui/src/themes/dark/link.ts

fix(ui/button,link): fix css color inherit

---

packages/varlet-ui/src/table/docs/en-US.md
packages/varlet-ui/src/table/docs/zh-CN.md
packages/varlet-ui/src/table/table.less
packages/varlet-ui/src/themes/dark/table.ts

fix(ui/table): fix css color inherit

---

packages/varlet-ui/src/dialog/dialog.less
packages/varlet-ui/src/dialog/docs/en-US.md
packages/varlet-ui/src/dialog/docs/zh-CN.md
packages/varlet-ui/src/themes/dark/dialog.ts

fix(ui/dialog): fix css color inherit

---

packages/varlet-ui/src/progress/docs/en-US.md
packages/varlet-ui/src/progress/docs/zh-CN.md
packages/varlet-ui/src/progress/progress.less
packages/varlet-ui/src/themes/dark/index.ts
packages/varlet-ui/src/themes/dark/progress.ts

fix(ui/progress): fix css color inherit

---

packages/varlet-ui/src/checkbox-group/docs/en-US.md
packages/varlet-ui/src/checkbox-group/docs/zh-CN.md
packages/varlet-ui/src/checkbox/checkbox.less
packages/varlet-ui/src/chip/chip.less
packages/varlet-ui/src/chip/docs/en-US.md
packages/varlet-ui/src/chip/docs/zh-CN.md
packages/varlet-ui/src/countdown/Countdown.vue
packages/varlet-ui/src/countdown/countdown.less
packages/varlet-ui/src/countdown/docs/en-US.md
packages/varlet-ui/src/countdown/docs/zh-CN.md
packages/varlet-ui/src/date-picker/date-picker.less
packages/varlet-ui/src/date-picker/docs/en-US.md
packages/varlet-ui/src/date-picker/docs/zh-CN.md
packages/varlet-ui/src/option/option.less
packages/varlet-ui/src/radio-group/docs/en-US.md
packages/varlet-ui/src/radio-group/docs/zh-CN.md
packages/varlet-ui/src/radio/radio.less
packages/varlet-ui/src/select/docs/en-US.md
packages/varlet-ui/src/select/docs/zh-CN.md
packages/varlet-ui/src/themes/dark/checkbox.ts
packages/varlet-ui/src/themes/dark/chip.ts
packages/varlet-ui/src/themes/dark/countdown.ts
packages/varlet-ui/src/themes/dark/datePicker.ts
packages/varlet-ui/src/themes/dark/index.ts
packages/varlet-ui/src/themes/dark/option.ts
packages/varlet-ui/src/themes/dark/radio.ts
packages/varlet-ui/src/themes/dark/timePicker.ts
packages/varlet-ui/src/time-picker/docs/en-US.md
packages/varlet-ui/src/time-picker/docs/zh-CN.md
packages/varlet-ui/src/time-picker/timePicker.less

fix(ui/time-picker, date-picker, option, radio, checkbox, chip, countdown): fix css color inherit

---

packages/varlet-ui/src/image-preview/ImagePreview.vue
packages/varlet-ui/src/image-preview/docs/en-US.md
packages/varlet-ui/src/image-preview/docs/zh-CN.md
packages/varlet-ui/src/image-preview/example/index.vue
packages/varlet-ui/src/image-preview/index.ts
packages/varlet-ui/src/image-preview/props.ts
packages/varlet-ui/types/imagePreview.d.ts

feat(image-preview): add initialIndex to specify initial position&three methods(prev, next, to) to control page

---

packages/varlet-ui/src/image-preview/__tests__/__snapshots__/component.spec.js.snap
packages/varlet-ui/src/image-preview/__tests__/component.spec.js
packages/varlet-ui/src/image-preview/__tests__/index.spec.js

test(image-preview): add test cases for initialIndex prop and prev & next & to methods

---

packages/varlet-ui/src/switch/Switch.vue
packages/varlet-ui/src/switch/example/index.vue
packages/varlet-ui/src/switch/switch.less

fix(switch): fix load animation without displaying when the radius isn't setting

---

packages/varlet-ui/src/input/Input.vue
packages/varlet-ui/src/input/__tests__/__snapshots__/index.spec.js.snap

---
#1112 
---
---
https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCB2YWx1ZTIgPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8dmFyLXNwYWNlIGRpcmVjdGlvbj1cImNvbHVtblwiIHNpemU9XCJsYXJnZVwiPlxuICAgICA8dmFyLWlucHV0IHBsYWNlaG9sZGVyPVwi5aeT5ZCNXCIgdi1tb2RlbD1cInZhbHVlXCIgdmFyaWFudD1cIm91dGxpbmVkXCIgLz5cbiAgICAgPHZhci1pbnB1dCBwbGFjZWhvbGRlcj1cIuWvhueggVwiIHYtbW9kZWw9XCJ2YWx1ZTJcIiB0eXBlPVwicGFzc3dvcmRcIiB2YXJpYW50PVwib3V0bGluZWRcIiAvPlxuICAgPC92YXItc3BhY2U+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG5cbjwvc3R5bGU+XG4iLCJBcHBXcmFwcGVyLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IGluc3RhbGxWYXJsZXRVSSB9IGZyb20gJy4vdmFybGV0LXJlcGwtcGx1Z2luLmpzJ1x …

fix(input): fix focus error when click tab and this form has password input

---

packages/varlet-ui/src/progress/__tests__/index.spec.js

test(progress): add test case for indeterminate

---

packages/varlet-ui/src/action-sheet/example/index.vue
packages/varlet-ui/src/app-bar/example/index.vue
packages/varlet-ui/src/avatar/example/index.vue
packages/varlet-ui/src/badge/example/index.vue
packages/varlet-ui/src/button/example/index.vue
packages/varlet-ui/src/chip/example/index.vue
packages/varlet-ui/src/ellipsis/example/index.vue
packages/varlet-ui/src/fab/example/index.vue
packages/varlet-ui/src/form/example/index.vue
packages/varlet-ui/src/image/example/index.vue
packages/varlet-ui/src/index-bar/example/index.vue
packages/varlet-ui/src/input/example/index.vue
packages/varlet-ui/src/link/example/index.vue
packages/varlet-ui/src/list/example/index.vue
packages/varlet-ui/src/loading-bar/example/index.vue
packages/varlet-ui/src/paper/example/index.vue
packages/varlet-ui/src/picker/example/index.vue
packages/varlet-ui/src/popup/example/index.vue
packages/varlet-ui/src/progress/example/index.vue
packages/varlet-ui/src/rate/example/index.vue
packages/varlet-ui/src/result/example/index.vue
packages/varlet-ui/src/select/example/index.vue
packages/varlet-ui/src/slider/example/index.vue
packages/varlet-ui/src/snackbar/example/index.vue
packages/varlet-ui/src/space/example/index.vue
packages/varlet-ui/src/sticky/example/index.vue
packages/varlet-ui/src/styles/example/index.vue
packages/varlet-ui/src/switch/example/index.vue
packages/varlet-ui/src/tabs/example/index.vue
packages/varlet-ui/src/tooltip/example/index.vue

docs: replace vw with vmin in example

---

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/slider/Slider.vue
packages/varlet-ui/src/slider/slider.less

fix(slider): fix bubble size of the Slider component is abnormal

---

packages/varlet-ui/src/divider/Divider.vue
packages/varlet-ui/src/divider/__tests__/index.spec.js
packages/varlet-ui/src/divider/divider.less
packages/varlet-ui/src/divider/docs/en-US.md
packages/varlet-ui/src/divider/docs/zh-CN.md

refactor(divider): refactor divider in vertical mode

---

packages/varlet-ui/src/switch/Switch.vue

style(switch): optimize code

---

packages/varlet-ui/src/fab/Fab.tsx
packages/varlet-ui/src/fab/__tests__/index.spec.js
packages/varlet-ui/src/fab/docs/en-US.md
packages/varlet-ui/src/fab/docs/zh-CN.md
packages/varlet-ui/src/fab/props.ts
packages/varlet-ui/types/fab.d.ts

feat(fab): support drag props for fab

---

packages/varlet-ui/src/avatar/Avatar.vue
packages/varlet-ui/src/avatar/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/avatar/__tests__/index.spec.js
packages/varlet-ui/src/avatar/docs/en-US.md
packages/varlet-ui/src/avatar/docs/zh-CN.md
packages/varlet-ui/src/avatar/props.ts
packages/varlet-ui/types/avatar.d.ts

feat(avatar): support image alt

---

.github/ISSUE_TEMPLATE/1-bug-report.md

feat(template): add reproduction link in bug report template

---

.github/PULL_REQUEST_TEMPLATE.md

chore: add issue and related links into pr template

---

packages/varlet-ui/src/drag/Drag.vue
packages/varlet-ui/src/drag/__tests__/index.spec.js
packages/varlet-ui/src/drag/docs/en-US.md
packages/varlet-ui/src/drag/docs/zh-CN.md
packages/varlet-ui/src/drag/props.ts
packages/varlet-ui/types/drag.d.ts

feat(drag): support click event

---

packages/varlet-ui/src/fab/Fab.tsx
packages/varlet-ui/src/image-preview/ImagePreview.vue

refactor(fab): replace dragging status with click event

---

.github/PULL_REQUEST_TEMPLATE.md

chore: optimize pr template

---

packages/varlet-ui/src/tooltip/docs/en-US.md
packages/varlet-ui/src/tooltip/docs/zh-CN.md

fix(tooltip-docs): typo

---

packages/varlet-ui/src/image-preview/ImagePreview.vue
packages/varlet-ui/src/image-preview/__tests__/component.spec.js
packages/varlet-use/src/useTouch.ts

refactor(image-preview): refactor by useTouch

---

packages/varlet-ui/src/link/Link.vue
packages/varlet-ui/src/link/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/link/__tests__/index.spec.js
packages/varlet-ui/src/link/docs/en-US.md
packages/varlet-ui/src/link/docs/zh-CN.md
packages/varlet-ui/src/link/props.ts
packages/varlet-ui/types/link.d.ts

feat(link): support rel attribute

---

packages/varlet-ui/src/swipe/docs/en-US.md
packages/varlet-ui/src/swipe/docs/zh-CN.md
packages/varlet-ui/src/swipe/example/index.vue

docs(swipe): modify custom indicator example

---

packages/varlet-ui/src/badge/badge.less
packages/varlet-ui/src/badge/docs/en-US.md
packages/varlet-ui/src/badge/docs/zh-CN.md

feat(badge): support custom content border

---

packages/varlet-ui/src/swipe/docs/en-US.md
packages/varlet-ui/src/swipe/docs/zh-CN.md

docs(swipe): fix incorrect spelling

---

packages/varlet-ui/src/uploader/Uploader.vue

fix(uploader): readonly mode allows to preview picture

---

packages/varlet-ui/src/select/select.less

fix(select): hidden vertical scroll bar

---

packages/varlet-ui/src/uploader/Uploader.vue

fix(uploader): convert default slot to boolean value

---

packages/varlet-ui/README.zh-CN.md

docs: rename the Chinese playground

---

packages/varlet-ui/src/popup/docs/zh-CN.md

docs(popup): typo

---

packages/varlet-ui/src/app-bar/AppBar.vue
packages/varlet-ui/src/avatar-group/AvatarGroup.vue
packages/varlet-ui/src/cell/Cell.vue

refactor(ui): replace type StyleValue with CSSProperties

---

packages/varlet-ui/src/ellipsis/Ellipsis.vue
packages/varlet-ui/src/ellipsis/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/ellipsis/__tests__/index.spec.js
packages/varlet-ui/src/ellipsis/docs/en-US.md
packages/varlet-ui/src/ellipsis/docs/zh-CN.md
packages/varlet-ui/src/ellipsis/example/index.vue
packages/varlet-ui/src/ellipsis/example/locale/en-US.ts
packages/varlet-ui/src/ellipsis/example/locale/zh-CN.ts
packages/varlet-ui/src/ellipsis/props.ts
packages/varlet-ui/types/ellipsis.d.ts

feat(ellipsis): support expand

---

packages/varlet-ui/src/badge/example/index.vue

- [ x ] Fix linting errors
- [ x ] Tests have been added / updated (or snapshots)
文档和 example 展示内容不一致，对齐位置

docs(badge): keep example and docs with same codes

---

packages/varlet-ui/src/uploader/Uploader.vue
packages/varlet-ui/src/uploader/__tests__/index.spec.js
packages/varlet-ui/src/uploader/docs/en-US.md
packages/varlet-ui/src/uploader/docs/zh-CN.md
packages/varlet-ui/src/uploader/example/index.vue
packages/varlet-ui/src/uploader/example/locale/en-US.ts
packages/varlet-ui/src/uploader/example/locale/zh-CN.ts
packages/varlet-ui/src/uploader/props.ts
packages/varlet-ui/types/uploader.d.ts

Added props preventDefaultPreview and event onPreview to support customized file preview
close #1203 .

Support custom preview for uploader component

---

packages/varlet-ui/src/uploader/docs/en-US.md

docs(uploader): typo

---

packages/varlet-cli/site/pc/components/AppSidebar.vue
packages/varlet-ui/src/ripple/index.ts

为文档上的菜单添加超链接能力，这样用户可以更方便的多开标签页
水波纹在元素被a标签包含的时候，无法正常结束，添加了 dragend 事件使其正常

feat(doc): Add hyperlink capability to document menu

---

packages/varlet-ui/src/action-sheet/actionSheet.less
packages/varlet-ui/src/action-sheet/docs/en-US.md
packages/varlet-ui/src/action-sheet/docs/zh-CN.md

feat(action-sheet): support setting action sheet border top style

---

packages/varlet-ui/src/swipe/Swipe.vue

refactor(swipe): optimize code

---

packages/varlet-ui/src/avatar/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/avatar/__tests__/index.spec.js
packages/varlet-ui/src/avatar/docs/en-US.md
packages/varlet-ui/src/avatar/docs/zh-CN.md
packages/varlet-ui/src/avatar/example/index.vue

test(avatar): complete test cases

---

packages/varlet-ui/src/avatar/__tests__/index.spec.js
packages/varlet-ui/src/avatar/docs/en-US.md
packages/varlet-ui/src/avatar/docs/zh-CN.md
packages/varlet-ui/src/avatar/example/index.vue

test(avatar): add hoverable test case

---

packages/varlet-ui/types/floatingPanel.d.ts
packages/varlet-ui/types/menu.d.ts
packages/varlet-ui/types/tooltip.d.ts

fix(ui): resolve conflict between menu and tooltip types

---

packages/varlet-ui/src/date-picker/date-picker.less
packages/varlet-ui/src/date-picker/docs/en-US.md
packages/varlet-ui/src/date-picker/docs/zh-CN.md
packages/varlet-ui/src/time-picker/docs/en-US.md
packages/varlet-ui/src/time-picker/docs/zh-CN.md
packages/varlet-ui/src/time-picker/timePicker.less

feat(time-picker, date-picker): support custom title height

---

packages/varlet-ui/src/time-picker/TimePicker.vue
packages/varlet-ui/src/time-picker/__tests__/index.spec.js
packages/varlet-ui/src/time-picker/docs/en-US.md
packages/varlet-ui/src/time-picker/docs/zh-CN.md
packages/varlet-ui/src/time-picker/props.ts
packages/varlet-ui/types/timePicker.d.ts

feat(time-picker): support titleColor

---

packages/varlet-ui/src/button-group/docs/zh-CN.md
packages/varlet-ui/src/button/docs/zh-CN.md
packages/varlet-ui/src/card/docs/zh-CN.md
packages/varlet-ui/src/fab/docs/zh-CN.md
packages/varlet-ui/src/floating-panel/docs/zh-CN.md

docs(ui): typo

---

packages/varlet-ui/src/date-picker/DatePicker.vue
packages/varlet-ui/src/date-picker/__tests__/index.spec.js
packages/varlet-ui/src/date-picker/docs/en-US.md
packages/varlet-ui/src/date-picker/docs/zh-CN.md
packages/varlet-ui/src/date-picker/props.ts
packages/varlet-ui/types/datePicker.d.ts

refactor(date-picker): replace headerColor with titleColor

---

packages/varlet-ui/src/counter/Counter.vue
packages/varlet-ui/src/counter/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/counter/__tests__/index.spec.js

test(counter): complete test cases

---

packages/varlet-ui/src/date-picker/DatePicker.vue
packages/varlet-ui/src/date-picker/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/date-picker/__tests__/index.spec.js
packages/varlet-ui/src/date-picker/date-picker.less
packages/varlet-ui/src/date-picker/docs/en-US.md
packages/varlet-ui/src/date-picker/docs/zh-CN.md
packages/varlet-ui/src/date-picker/props.ts
packages/varlet-ui/src/locale/en-US.ts
packages/varlet-ui/src/locale/index.ts
packages/varlet-ui/src/locale/zh-CN.ts
packages/varlet-ui/types/datePicker.d.ts

feat(date-picker): suport hint

---

packages/varlet-ui/src/chip/Chip.vue
packages/varlet-ui/src/chip/__tests__/index.spec.js
packages/varlet-ui/src/chip/docs/en-US.md
packages/varlet-ui/src/chip/docs/zh-CN.md
packages/varlet-ui/src/chip/example/index.vue
packages/varlet-ui/src/chip/props.ts
packages/varlet-ui/src/select/Select.vue
packages/varlet-ui/types/chip.d.ts

refactor(chip): rename closable to closeable

---

packages/varlet-ui/src/switch/Switch.vue
packages/varlet-ui/src/switch/props.ts
packages/varlet-ui/types/switch.d.ts

fix(switch): change type of the click event from MouseEvent to Event

---

packages/varlet-ui/src/collapse/__tests__/index.spec.js
packages/varlet-ui/src/input/__tests__/index.spec.js
packages/varlet-ui/src/menu/__tests__/index.spec.js
packages/varlet-ui/src/popup/__tests__/index.spec.js
packages/varlet-ui/src/progress/__tests__/index.spec.js
packages/varlet-ui/src/pull-refresh/__tests__/index.spec.js
packages/varlet-ui/src/result/__tests__/index.spec.js
packages/varlet-ui/src/snackbar/__tests__/component.spec.js
packages/varlet-ui/src/style-provider/__tests__/index.spec.js
packages/varlet-ui/src/switch/__tests__/index.spec.js
packages/varlet-ui/src/tooltip/__tests__/index.spec.js

test(ui): unmount wrapper after end of test

---

packages/varlet-ui/src/back-top/BackTop.vue
packages/varlet-ui/src/back-top/__tests__/index.spec.js
packages/varlet-ui/src/back-top/docs/en-US.md
packages/varlet-ui/src/back-top/docs/zh-CN.md
packages/varlet-ui/src/back-top/example/index.vue
packages/varlet-ui/src/back-top/example/locale/en-US.ts
packages/varlet-ui/src/back-top/example/locale/index.ts
packages/varlet-ui/src/back-top/example/locale/zh-CN.ts
packages/varlet-ui/src/back-top/props.ts
packages/varlet-ui/types/backTop.d.ts

fix(back-top): change type of the click event from MouseEvent to Event

---

packages/varlet-ui/src/table/__tests__/index.spec.js

test(table): complete test cases

---

packages/varlet-ui/src/swipe/docs/en-US.md
packages/varlet-ui/src/swipe/docs/zh-CN.md
packages/varlet-ui/src/swipe/swipe.less

https://github.com/varletjs/varlet/assets/70570907/2bf501c5-a9b8-4092-b434-1c060ac4d866

feat(swipe): support --swipe-navigation-z-index

---

packages/varlet-ui/src/card/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/card/__tests__/index.spec.js
packages/varlet-ui/src/card/docs/en-US.md
packages/varlet-ui/src/card/docs/zh-CN.md
packages/varlet-ui/src/card/example/index.vue
packages/varlet-ui/src/card/example/locale/zh-CN.ts

test(card): complete test cases

---

packages/varlet-ui/src/rate/__tests__/index.spec.js

test(rate): complete test cases

---

README.md
README.zh-CN.md

docs: add Ecosystem

---

README.md
README.zh-CN.md
packages/varlet-ui/README.md
packages/varlet-ui/README.zh-CN.md
packages/varlet-ui/docs/home.en-US.md
packages/varlet-ui/docs/home.zh-CN.md

docs: add official and community ecosystem in readme and docs

---

packages/varlet-ui/src/loading/docs/en-US.md
packages/varlet-ui/src/loading/docs/zh-CN.md
packages/varlet-ui/src/loading/loading.less

fix(loading): add missing --loading-color &  support --loading-desc-color

---

packages/varlet-ui/src/countdown/countdown.less
packages/varlet-ui/src/countdown/docs/en-US.md
packages/varlet-ui/src/countdown/docs/zh-CN.md

feat(countdown): support --countdown-text-font-size

---

packages/varlet-ui/src/option/option.less

[playground](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHZhci1zcGFjZSBkaXJlY3Rpb249XCJjb2x1bW5cIiBzaXplPVwibGFyZ2VcIj5cbiAgICA8dmFyLXNlbGVjdCBwbGFjZWhvbGRlcj1cIuivt+mAieaLqeS4gOS4qumAiemhuVwiIHYtbW9kZWw9XCJ2YWx1ZVwiPlxuICAgICAgPHZhci1vcHRpb24gbGFiZWw9XCJLRkNWTUU1MO+8jOi/meS8vOS5juaYr+afkOS4quelnuenmOeahOS7o+eggeOAguafkOWkqe+8jOWwj+aYjuWcqOiCr+W+t+WfuumkkOWOheeCuemkkOaXtu+8jOaEj+Wklui+k+WFpeS6hui/meS4quS7o+egge+8jOe7k+aenOWHuueOsOS6huS4gOS7veS7juacquingei/h+eahOi2hee6p+ixquWNjuWll+mkkOOAguS7luWFtOWli+WcsOWTgeWwne+8jOWPkeeOsOi/meeugOebtOaYr+WRs+iVvueahOebm+WutOOAguS7juatpO+8jEtGQ1ZNRTUw5oiQ5LqG5bCP5 …

fix(ui/Option): ellipses are not displayed when text overflows

---

packages/varlet-ui/src/paper/docs/en-US.md
packages/varlet-ui/src/paper/docs/zh-CN.md

docs(paper): modify the default value of ripple to false

---

packages/varlet-ui/src/counter/__tests__/index.spec.js

test(counter): correct invalid prop type

---

packages/varlet-ui/src/skeleton/docs/en-US.md
packages/varlet-ui/src/skeleton/docs/zh-CN.md
packages/varlet-ui/src/skeleton/example/index.vue
packages/varlet-ui/src/skeleton/example/locale/en-US.ts
packages/varlet-ui/src/skeleton/example/locale/zh-CN.ts

docs(skeleton): modify the default value of skeleton prop in docs

---

packages/varlet-ui/src/back-top/docs/en-US.md
packages/varlet-ui/src/back-top/docs/zh-CN.md

docs(back-top): modify the default value of right and bottom prop

---

packages/varlet-ui/src/switch/docs/en-US.md
packages/varlet-ui/src/switch/docs/zh-CN.md

docs(switch): modify the default value of switch

---

packages/varlet-ui/src/index-bar/IndexBar.vue
packages/varlet-ui/src/index-bar/__tests__/index.spec.js
packages/varlet-ui/src/index-bar/docs/en-US.md
packages/varlet-ui/src/index-bar/docs/zh-CN.md
packages/varlet-ui/src/index-bar/example/index.vue
packages/varlet-ui/src/index-bar/example/locale/en-US.ts
packages/varlet-ui/src/index-bar/example/locale/zh-CN.ts

docs(index-bar): modify the default value of highlightColor

---

packages/varlet-ui/src/ellipsis/Ellipsis.vue
packages/varlet-ui/src/ellipsis/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/ellipsis/__tests__/index.spec.js

fix(ellipsis): spread types may only be created from object types

---

packages/varlet-ui/src/uploader/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/uploader/__tests__/index.spec.js

test(uploader): complete test cases

---

packages/varlet-ui/src/uploader/docs/en-US.md
packages/varlet-ui/src/uploader/docs/zh-CN.md
packages/varlet-ui/src/uploader/example/locale/en-US.ts

docs(uploader): add missing onClickAction event

---

packages/varlet-ui/src/fab/example/index.vue
packages/varlet-ui/src/floating-panel/example/index.vue
packages/varlet-ui/src/form/example/index.vue
packages/varlet-ui/src/hover/example/index.vue
packages/varlet-ui/src/icon/example/index.vue
packages/varlet-ui/src/image-preview/example/index.vue
packages/varlet-ui/src/image/example/index.vue
packages/varlet-ui/src/index-bar/example/index.vue
packages/varlet-ui/src/input/example/index.vue

style(example): optimize code styles (F-J)

---

packages/varlet-ui/src/image-preview/ImagePreview.vue
packages/varlet-ui/src/image-preview/__tests__/__snapshots__/component.spec.js.snap
packages/varlet-ui/src/image-preview/__tests__/component.spec.js
packages/varlet-ui/src/image-preview/docs/en-US.md
packages/varlet-ui/src/image-preview/docs/zh-CN.md

feat(image-preview): support zoom method

---

packages/varlet-ui/src/button/Button.vue
packages/varlet-ui/src/button/button.less

fix(button): remove hover and ripple effect while loading

---

packages/varlet-ui/src/link/example/index.vue
packages/varlet-ui/src/list/example/index.vue
packages/varlet-ui/src/loading-bar/example/index.vue
packages/varlet-ui/src/loading/example/index.vue
packages/varlet-ui/src/menu-select/example/index.vue
packages/varlet-ui/src/menu/example/index.vue
packages/varlet-ui/src/overlay/example/index.vue
packages/varlet-ui/src/pagination/example/Basic.vue
packages/varlet-ui/src/pagination/example/Disabled.vue
packages/varlet-ui/src/pagination/example/QuickJumper.vue
packages/varlet-ui/src/pagination/example/ShowTotal.vue
packages/varlet-ui/src/pagination/example/SizeOption.vue
packages/varlet-ui/src/pagination/example/index.vue
packages/varlet-ui/src/paper/example/index.vue
packages/varlet-ui/src/picker/example/index.vue
packages/varlet-ui/src/popup/example/index.vue
packages/varlet-ui/src/progress/example/index.vue
packages/varlet-ui/src/pull-refresh/example/index.vue

style(example): optimize code styles (K-P)

---

packages/varlet-cli/README.md
packages/varlet-cli/README.zh-CN.md

docs(cli): add the solution of failing to install sharp in readme

---

packages/varlet-ui/src/radio-group/example/index.vue
packages/varlet-ui/src/rate/example/index.vue
packages/varlet-ui/src/result/example/index.vue
packages/varlet-ui/src/row/example/index.vue
packages/varlet-ui/src/select/example/index.vue
packages/varlet-ui/src/skeleton/example/index.vue
packages/varlet-ui/src/slider/example/index.vue
packages/varlet-ui/src/snackbar/example/index.vue
packages/varlet-ui/src/space/example/index.vue
packages/varlet-ui/src/steps/example/index.vue
packages/varlet-ui/src/sticky/example/index.vue
packages/varlet-ui/src/style-provider/example/index.vue
packages/varlet-ui/src/styles/example/index.vue
packages/varlet-ui/src/swipe/example/index.vue
packages/varlet-ui/src/switch/example/index.vue
packages/varlet-ui/src/tab-item/example/index.vue
packages/varlet-ui/src/table/example/Basic.vue
packages/varlet-ui/src/table/example/FooterSlots.vue
packages/varlet-ui/src/table/example/index.vue
packages/varlet-ui/src/tabs-items/example/index.vue
packages/varlet-ui/src/tabs/example/index.vue
packages/varlet-ui/src/themes/example/index.vue
packages/varlet-ui/src/time-picker/example/index.vue
packages/varlet-ui/src/tooltip/example/index.vue
packages/varlet-ui/src/watermark/example/index.vue

style(example): optimize code styles (Q-Z)

---

packages/varlet-ui/docs/cli.en-US.md
packages/varlet-ui/docs/cli.zh-CN.md

docs(ui): add the solution of failing to install sharp in cli readme

---

packages/varlet-ui/src/progress/docs/en-US.md
packages/varlet-ui/src/progress/docs/zh-CN.md

docs(progress): modify the default value of  track-color

---

packages/varlet-ui/src/chip/docs/en-US.md

docs(chip): highlight type attribute in en-US docs

---

packages/varlet-ui/src/utils/elements.ts

types(ui): correct the return type of toSizeUnit

---

packages/varlet-ui/src/link/Link.vue
packages/varlet-ui/src/link/__tests__/index.spec.js
packages/varlet-ui/src/link/docs/en-US.md
packages/varlet-ui/src/link/example/locale/en-US.ts

refactor(link): optimize code

---

packages/varlet-ui/src/icon/docs/en-US.md
packages/varlet-ui/src/icon/docs/zh-CN.md
packages/varlet-ui/src/icon/example/index.vue
packages/varlet-ui/src/icon/example/locale/en-US.ts
packages/varlet-ui/src/icon/example/locale/zh-CN.ts

WIP docs(icon): remove unused variable and optimize examples

---

packages/varlet-ui/src/sticky/docs/en-US.md
packages/varlet-ui/src/sticky/docs/zh-CN.md

docs(sticky): correct the default value of z-index

---

packages/varlet-ui/src/radio-group/docs/en-US.md
packages/varlet-ui/src/radio-group/docs/zh-CN.md
packages/varlet-ui/src/radio/docs/en-US.md
packages/varlet-ui/src/radio/docs/zh-CN.md

docs(radio): correct the type of checkedColor and uncheckedColor

---

packages/varlet-ui/src/checkbox-group/docs/en-US.md
packages/varlet-ui/src/checkbox-group/docs/zh-CN.md
packages/varlet-ui/src/checkbox/docs/en-US.md
packages/varlet-ui/src/checkbox/docs/zh-CN.md

docs(checkbox): correct the type of checkedColor and uncheckedColor

---

packages/varlet-ui/src/slider/docs/en-US.md
packages/varlet-ui/src/slider/docs/zh-CN.md
packages/varlet-ui/src/slider/slider.less

feat(slider): support custom styles by css var

---

packages/varlet-ui/src/button/index.ts
packages/varlet-ui/src/utils/__tests__/components.spec.js
packages/varlet-ui/src/utils/components.ts
packages/varlet-ui/types/button.d.ts
packages/varlet-ui/types/varComponent.d.ts

feat: support static method setPropsDefaults

---

packages/varlet-ui/src/cell/docs/en-US.md
packages/varlet-ui/src/cell/docs/zh-CN.md

docs(cell): docs and example remain consistent

---

packages/varlet-ui/src/rate/docs/en-US.md
packages/varlet-ui/src/rate/docs/zh-CN.md

docs(rate): remove the default value of disabledColor

---

packages/varlet-ui/src/rate/docs/en-US.md
packages/varlet-ui/src/rate/docs/zh-CN.md
packages/varlet-ui/src/rate/rate.less

feat(rate): support --rate-size

---

packages/varlet-ui/src/chip/Chip.vue
packages/varlet-ui/src/chip/docs/en-US.md
packages/varlet-ui/src/chip/docs/zh-CN.md
packages/varlet-ui/src/chip/example/index.vue

types(chip): add the return type for computed properties

---

packages/varlet-ui/src/tab/Tab.vue
packages/varlet-ui/src/tab/docs/en-US.md
packages/varlet-ui/src/tab/docs/zh-CN.md
packages/varlet-ui/src/tab/props.ts
packages/varlet-ui/src/tabs/docs/en-US.md
packages/varlet-ui/src/tabs/docs/zh-CN.md

feat(tab): support ripple

---

packages/varlet-ui/src/tab/docs/en-US.md
packages/varlet-ui/src/tab/docs/zh-CN.md
packages/varlet-ui/src/tabs/docs/en-US.md
packages/varlet-ui/src/tabs/docs/zh-CN.md

docs(tabs): typo

---

packages/varlet-ui/src/tab/tab.less
packages/varlet-ui/src/tabs/docs/en-US.md
packages/varlet-ui/src/tabs/docs/zh-CN.md

feat(tab): support --tab-font-weight

---

packages/varlet-shared/src/is.ts

fix(shared): adapt to `-` and `+` for `isNumeric`

---

packages/varlet-ui/src/date-picker/src/day-picker-panel.vue

refactor(date-picker): use spread operator to replace concat method

---

packages/varlet-ui/src/collapse/Collapse.vue
packages/varlet-ui/src/collapse/__tests__/index.spec.js
packages/varlet-ui/src/collapse/provide.ts

refactor(collapse): merge logic of matching names and indexes

---

packages/varlet-ui/src/badge/Badge.vue
packages/varlet-ui/src/badge/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/badge/__tests__/index.spec.js
packages/varlet-ui/src/badge/badge.less
packages/varlet-ui/src/badge/docs/en-US.md
packages/varlet-ui/src/badge/docs/zh-CN.md
packages/varlet-ui/src/badge/example/index.vue
packages/varlet-ui/src/badge/example/locale/en-US.ts
packages/varlet-ui/src/badge/example/locale/zh-CN.ts
packages/varlet-ui/src/badge/props.ts
packages/varlet-ui/types/badge.d.ts

feat(badge): support offsetX and offsetY

---

packages/varlet-ui/src/collapse/Collapse.vue

refactor(collapse): don't process array when accordion is true

---

packages/varlet-ui/src/ellipsis/docs/en-US.md
packages/varlet-ui/src/ellipsis/example/locale/en-US.ts

docs(ellipsis): capitalize title

---

packages/varlet-ui/src/button/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/button/__tests__/index.spec.js

test(button): complete test cases

---

packages/varlet-ui/types/styleVars.d.ts

style(date-picker): add missing types

---

packages/varlet-cli/src/node/commands/icons.ts

refactor(cli): optimize judgment condition to filter svg files

---

packages/varlet-ui/src/collapse/docs/en-US.md
packages/varlet-ui/src/collapse/docs/zh-CN.md
packages/varlet-ui/src/collapse/example/index.vue
packages/varlet-ui/src/collapse/example/locale/en-US.ts
packages/varlet-ui/src/collapse/example/locale/zh-CN.ts

docs(collapse): optimize docs

---

packages/varlet-ui/src/collapse/__tests__/index.spec.js

test(collapse): complete test cases

---

packages/varlet-cli/site/pc/components/AppHeader.vue
packages/varlet-cli/src/node/config/varlet.default.config.ts

feat(site): add changelog entry in header for pc

---

packages/varlet-ui/src/slider/Slider.vue
packages/varlet-ui/src/slider/__tests__/index.spec.js

fix(slider): remove the logic for thumb to double in size

---

packages/varlet-cli/site/pc/components/AppSidebar.vue

feat(site): hide link when menu type is title

---

packages/varlet-ui/src/drag/example/index.vue

docs(drag): reduce zIndex of disabled button

---

packages/varlet-icons/svg/uF135-bookmark.svg
packages/varlet-icons/svg/uF136-bookmark-outline.svg

feat(icons): support bookmark icon

---

packages/varlet-ui/src/time-picker/TimePicker.vue
packages/varlet-ui/src/time-picker/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/time-picker/docs/en-US.md
packages/varlet-ui/src/time-picker/docs/zh-CN.md
packages/varlet-ui/src/time-picker/timePicker.less
packages/varlet-ui/types/styleVars.d.ts
packages/varlet-ui/types/timePicker.d.ts

- add slot named actions in the bottom area
The issues you want to close, formatted as close #1333 .

feat(time-picker): support actions slot

---

packages/varlet-ui/src/chip/Chip.vue
packages/varlet-ui/src/chip/props.ts
packages/varlet-ui/types/chip.d.ts

refactor(chip): remove closable prop

---

packages/varlet-ui/src/progress/Progress.vue
packages/varlet-ui/src/progress/__tests__/index.spec.js
packages/varlet-ui/src/progress/docs/en-US.md
packages/varlet-ui/src/progress/docs/zh-CN.md
packages/varlet-ui/src/progress/progress.less
packages/varlet-ui/src/progress/props.ts
packages/varlet-ui/types/progress.d.ts

refactor(progress): remove ripple prop

---

packages/varlet-ui/types/imagePreview.d.ts

types(image-preview): add missing zoom method

---

packages/varlet-ui/src/image-preview/ImagePreview.vue
packages/varlet-ui/src/image-preview/props.ts
packages/varlet-ui/types/imagePreview.d.ts

refactor(image-preview): remove current prop

---

packages/varlet-ui/src/loading-bar/index.ts
packages/varlet-ui/types/loadingBar.d.ts

refactor(loading-bar): remove mergeConfig method

---

packages/varlet-ui/src/index-bar/IndexBar.vue
packages/varlet-ui/src/index-bar/props.ts
packages/varlet-ui/types/indexBar.d.ts

refactor(index-bar): remove cssMode prop

---

packages/varlet-ui/src/image-preview/index.ts

refactor(image-preview): remove current prop for function call

---

packages/varlet-ui/src/time-picker/TimePicker.vue
packages/varlet-ui/src/time-picker/__tests__/index.spec.js
packages/varlet-ui/src/time-picker/props.ts
packages/varlet-ui/types/timePicker.d.ts

refactor(time-picker): remove headerColor prop

---

packages/varlet-ui/src/date-picker/DatePicker.vue
packages/varlet-ui/src/date-picker/__tests__/index.spec.js
packages/varlet-ui/src/date-picker/props.ts
packages/varlet-ui/types/datePicker.d.ts

refactor(date-picker): remove headerColor prop

---

packages/varlet-ui/src/step/step.less
packages/varlet-ui/src/steps/docs/en-US.md
packages/varlet-ui/src/steps/docs/zh-CN.md
packages/varlet-ui/types/styleVars.d.ts

refactor(steps): remove --step-line-size and --step-min-size

---

packages/varlet-ui/src/snackbar/core.vue

fix(snackbar): hidden action element when no action slot

---

packages/varlet-ui/src/field-decorator/FieldDecorator.vue
packages/varlet-ui/src/input/Input.vue
packages/varlet-ui/src/input/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/input/__tests__/index.spec.js
packages/varlet-ui/src/input/docs/en-US.md
packages/varlet-ui/src/input/docs/zh-CN.md
packages/varlet-ui/src/select/Select.vue
packages/varlet-ui/src/select/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/select/__tests__/index.spec.js
packages/varlet-ui/src/select/docs/en-US.md
packages/varlet-ui/src/select/docs/zh-CN.md
packages/varlet-ui/types/input.d.ts
packages/varlet-ui/types/select.d.ts

feat(input, select): support clear icon slot

---

packages/varlet-ui/src/select/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/select/__tests__/index.spec.js

test(select): complete test cases

---

packages/varlet-ui-playground/src/download/download.ts

docs(playground): add missing import for Dialog component

---

packages/varlet-icons/svg/uF137-arrow-up-bold-box.svg
packages/varlet-icons/svg/uF138-arrow-up-bold-box-outline.svg

feat(icons): support arrow up bold box icon

---

packages/varlet-ui/src/avatar/Avatar.vue
packages/varlet-ui/src/back-top/BackTop.vue
packages/varlet-ui/src/collapse-item/CollapseItem.vue
packages/varlet-ui/src/floating-panel/FloatingPanel.vue
packages/varlet-ui/src/index-anchor/IndexAnchor.vue
packages/varlet-ui/src/index-bar/IndexBar.vue
packages/varlet-ui/src/rate/Rate.vue
packages/varlet-ui/src/slider/Slider.vue
packages/varlet-ui/src/time-picker/TimePicker.vue
packages/varlet-ui/src/time-picker/clock.vue

refactor(ui): replace HTMLDivElement with HTMLElement

---

packages/varlet-ui/src/swipe/Swipe.vue

style(swipe): format code

---

packages/varlet-ui/src/image-preview/ImagePreview.vue
packages/varlet-ui/src/image-preview/__tests__/__snapshots__/component.spec.js.snap

fix(image-preview): hidden extra element when no extra slot

---

packages/varlet-ui/src/checkbox-group/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/checkbox/Checkbox.vue
packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap

fix(checkbox): hidden default element when no default slot

---

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/radio-group/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/radio/Radio.vue

fix(radio): hidden default element when no default slot

---

packages/varlet-ui/src/collapse/__tests__/index.spec.js

Update test case for component Collapse

test(collapse): update test cases

---

packages/varlet-ui/src/step/Step.vue

fix(step): hidden default element when no default slot

---

packages/varlet-ui/src/skeleton/docs/en-US.md
packages/varlet-ui/src/skeleton/docs/zh-CN.md

docs(skeleton): update default value of rowsWidth

---

packages/varlet-ui/src/fab/docs/en-US.md
packages/varlet-ui/src/fab/docs/zh-CN.md

docs(fab): improve docs

---

packages/varlet-cli/site/mobile/App.vue
packages/varlet-ui/src/checkbox/provide.ts
packages/varlet-ui/types/form.d.ts

refactor(ui): use import type replace import for interface

---

packages/varlet-ui/src/index-bar/IndexBar.vue
packages/varlet-ui/src/index-bar/docs/en-US.md
packages/varlet-ui/src/index-bar/docs/zh-CN.md
packages/varlet-ui/types/indexBar.d.ts

feat(index-bar): support anchor name slot

---

packages/varlet-cli/src/node/commands/icons.ts

Fixed build icons failure when running pnpm run bootstrap

---

packages/varlet-ui/src/counter/docs/en-US.md
packages/varlet-ui/src/counter/docs/zh-CN.md

docs(counter): add missing lazy-change prop

---

packages/varlet-ui/src/counter/docs/en-US.md
packages/varlet-ui/src/counter/docs/zh-CN.md

docs(counter): correct type and default value of button-size prop

---

packages/varlet-ui/src/checkbox-group/docs/en-US.md
packages/varlet-ui/src/checkbox/docs/en-US.md
packages/varlet-ui/src/radio/docs/zh-CN.md

docs(checkbox&radio): correct typo in escape character

---

packages/varlet-ui/src/counter/docs/en-US.md
packages/varlet-ui/src/counter/docs/zh-CN.md

docs(counter): correct default value of step prop

---

packages/varlet-ui/src/image-preview/__tests__/__snapshots__/component.spec.js.snap
packages/varlet-ui/src/popup/Popup.tsx
packages/varlet-ui/src/popup/docs/en-US.md
packages/varlet-ui/src/popup/docs/zh-CN.md
packages/varlet-ui/src/popup/popup.less

fix(popup): allow click through when overlay is false

---

packages/varlet-cli/src/node/commands/lint.ts

fix(cli): add missing shared package for lint command and remove useless path

---

packages/varlet-ui/src/rate/docs/en-US.md
packages/varlet-ui/src/rate/docs/zh-CN.md
packages/varlet-ui/src/rate/props.ts
packages/varlet-ui/types/rate.d.ts

types(rate): correct the type of rules prop

---

packages/varlet-ui/src/checkbox-group/docs/en-US.md
packages/varlet-ui/src/checkbox-group/docs/zh-CN.md
packages/varlet-ui/src/checkbox-group/example/index.vue
packages/varlet-ui/src/picker/Picker.vue

- 调整Checkbox示例中「复选框组」下按钮位置
- 格式化Picker代码

docs(checkbox): modify use case

---

packages/varlet-ui/src/slider/docs/en-US.md
packages/varlet-ui/src/slider/docs/zh-CN.md

docs(slider): improve description about range example

---

packages/varlet-ui/src/slider/docs/en-US.md
packages/varlet-ui/src/slider/docs/zh-CN.md
packages/varlet-ui/src/slider/props.ts
packages/varlet-ui/types/slider.d.ts

types(slider): correct the type of rules prop

---

packages/varlet-ui/src/menu-select/docs/en-US.md
packages/varlet-ui/src/menu-select/docs/zh-CN.md

docs(menu-select): add missing menu option document

---

packages/varlet-ui/src/dialog/__tests__/component.spec.js

test(dialog): complete component test cases

---

packages/varlet-ui/src/bottom-navigation-item/BottomNavigationItem.vue

refactor(bottom-navigation-item): optimize code

---

packages/varlet-ui/src/menu/usePopover.ts

fix(menu): don't compute hostSize when no host element

---

packages/varlet-ui/src/index-anchor/IndexAnchor.vue
packages/varlet-ui/src/index-anchor/provide.ts
packages/varlet-ui/src/index-bar/IndexBar.vue
packages/varlet-ui/src/index-bar/__tests__/index.spec.js

修复index-bar组件的索引错误 
close #1436

fix(index-bar): 索引错误

---

packages/varlet-ui/src/tooltip/docs/en-US.md
packages/varlet-ui/src/tooltip/docs/zh-CN.md

docs(tooltip): correct the default value of placement prop

---

packages/varlet-ui/src/tabs/tabs.less

fix(tabs): hidden scrollbar for firefox

---

packages/varlet-ui/src/index-bar/IndexBar.vue

fix(index-bar): init scroller when start to scroll for nuxt

---

packages/varlet-ui/src/popup/popup.less

fix(popup): hidden scrollbar when show popup in bottom for firefox

---

packages/varlet-ui/src/popup/popup.less

fix(popup): correct the value of scrollbar-width

---

packages/varlet-ui/src/menu-select/props.ts
packages/varlet-ui/src/select/props.ts

types(select, menu-select): correct modelValue type

---

packages/varlet-ui/src/uploader/Uploader.vue
packages/varlet-ui/src/uploader/__tests__/__snapshots__/index.spec.js.snap

perf(uploader): improve accessibility

---

packages/varlet-ui/src/image-preview/ImagePreview.vue
packages/varlet-ui/src/image-preview/__tests__/__snapshots__/component.spec.js.snap

perf(image-preview): improve accessibility

---

packages/varlet-ui/src/avatar/Avatar.vue
packages/varlet-ui/src/avatar/__tests__/__snapshots__/index.spec.js.snap

perf(avatar): improve accessibility

---

packages/varlet-ui/src/image/Image.vue

perf(image): improve accessibility

---

packages/varlet-ui/src/picker/example/index.vue
packages/varlet-ui/src/picker/example/locale/zh-CN.ts

docs(picker): correct the contents of the Value Mapping button

---

packages/varlet-ui/src/date-picker/example/index.vue
packages/varlet-ui/src/pagination/example/QuickJumper.vue

docs(date-picker, pagination): remove defined or imported but unused variables

---

packages/varlet-ui/types/styleVars.d.ts

types(style-vars): add missing css vars

---

packages/varlet-ui/src/uploader/props.ts
packages/varlet-ui/types/uploader.d.ts

types(uploader): use a more accurate type for capture attribute

---

packages/varlet-ui/src/image/props.ts
packages/varlet-ui/src/input/props.ts
packages/varlet-ui/types/image.d.ts
packages/varlet-ui/types/input.d.ts

types(input): use a more accurate type for enterkeyhint attribute

---

README.md
README.zh-CN.md
packages/varlet-ui/README.md
packages/varlet-ui/README.zh-CN.md
packages/varlet-ui/docs/home.en-US.md
packages/varlet-ui/docs/home.zh-CN.md
packages/varlet-ui/docs/importOnDemand.en-US.md
packages/varlet-ui/docs/importOnDemand.zh-CN.md

docs: add @varlet/import-resolver in readme and site

---

packages/varlet-ui/src/uploader/__tests__/index.spec.js

refactor(uploader): remove unused import

---

packages/varlet-ui/src/link/docs/en-US.md
packages/varlet-ui/src/uploader/__tests__/index.spec.js

docs(link): add missing css var

---

packages/varlet-cli/template/create/__tests__/index.spec.js.ejs

refactor(cli): update create command

---

packages/varlet-ui/src/action-sheet/ActionItem.vue

refactor(action-sheet): remove unused import

---

packages/varlet-ui/src/select/docs/en-US.md
packages/varlet-ui/src/select/docs/zh-CN.md

docs(ui/select): fix close event

---

packages/varlet-ui/src/action-sheet/docs/en-US.md
packages/varlet-ui/src/action-sheet/docs/zh-CN.md
packages/varlet-ui/src/action-sheet/index.ts
packages/varlet-ui/src/action-sheet/props.ts
packages/varlet-ui/types/actionSheet.d.ts

docs(action-sheet): add close-on-key-escape api

---

packages/varlet-ui/src/dialog/dialog.less

fix(dialog): hidden corners when border radius isn't empty

---

packages/varlet-ui/src/dialog/Dialog.vue
packages/varlet-ui/src/dialog/docs/en-US.md
packages/varlet-ui/src/dialog/docs/zh-CN.md
packages/varlet-ui/src/dialog/index.ts
packages/varlet-ui/src/dialog/props.ts
packages/varlet-ui/types/dialog.d.ts

docs(dialog): add closeOnKeyEscape prop and onKeyEscape event

---

packages/varlet-ui/src/image-preview/docs/en-US.md
packages/varlet-ui/src/image-preview/docs/zh-CN.md
packages/varlet-ui/src/image-preview/index.ts
packages/varlet-ui/src/image-preview/props.ts
packages/varlet-ui/types/imagePreview.d.ts

docs(image-preview): add closeOnKeyEscape prop and onKeyEscape event

---

packages/varlet-ui/src/menu/docs/en-US.md
packages/varlet-ui/src/menu/docs/zh-CN.md
packages/varlet-ui/src/menu/props.ts
packages/varlet-ui/src/menu/usePopover.ts
packages/varlet-ui/types/menu.d.ts

docs(menu): add closeOnKeyEscape prop

---

packages/varlet-ui/src/overlay/docs/en-US.md
packages/varlet-ui/src/overlay/docs/zh-CN.md
packages/varlet-ui/src/overlay/props.ts
packages/varlet-ui/types/overlay.d.ts

docs(overlay): add closeOnKeyEscape prop and onKeyEscape event

---

packages/varlet-cli/src/node/commands/icons.ts

style(cli): remove unused type imports

---

packages/varlet-ui/src/hover/index.ts

fix(hover):  don't update style when no element for nuxt

---

packages/varlet-ui/src/popup/docs/en-US.md
packages/varlet-ui/src/popup/docs/zh-CN.md
packages/varlet-ui/src/popup/props.ts
packages/varlet-ui/types/popup.d.ts

docs(popup): add closeOnKeyEscape prop and onKeyEscape event

---

packages/varlet-ui/src/picker/docs/en-US.md
packages/varlet-ui/src/picker/docs/zh-CN.md
packages/varlet-ui/src/picker/index.ts
packages/varlet-ui/src/picker/props.ts
packages/varlet-ui/types/picker.d.ts

docs(picker): add closeOnKeyEscape prop and onKeyEscape event

---

packages/varlet-ui/src/tooltip/docs/en-US.md
packages/varlet-ui/src/tooltip/docs/zh-CN.md
packages/varlet-ui/src/tooltip/props.ts
packages/varlet-ui/types/tooltip.d.ts

docs(tooltip): add closeOnKeyEscape prop

---

packages/varlet-ui/src/button/Button.vue
packages/varlet-ui/src/floating-panel/FloatingPanel.vue
packages/varlet-ui/src/select/useSelectController.ts
packages/varlet-use/src/useVModel.ts

refactor: optimize code

---

packages/varlet-ui/src/back-top/BackTop.vue

fix(back-top): update backTop component visibility after mounting

---

packages/varlet-ui/src/sticky/Sticky.vue

fix the Sticky component error on first navigation
close #1529 .

fix: fix the Sticky component error on first navigation

---

packages/varlet-ui/src/countdown/__tests__/index.spec.js
packages/varlet-ui/src/slider/__tests__/index.spec.js

Modified Countdown test case to mock performance.now

refactor(test): in countdown mock performan.now

---

packages/varlet-ui/src/table/table.less

refactor(table): remove useless style

---

packages/varlet-ui/src/table/table.less

refactor(table): clean useless styles

---

packages/varlet-ui/src/dialog/docs/en-US.md
packages/varlet-ui/src/dialog/docs/zh-CN.md
packages/varlet-ui/src/dialog/example/index.vue
packages/varlet-ui/src/dialog/example/locale/en-US.ts

docs(dialog): optimize example code

---

packages/varlet-vite-plugins/src/inlineCss.ts

refactor(vite-plugin/inlineCss): remove deadcode

---

packages/varlet-preset-tailwindcss/package.json
pnpm-lock.yaml

chore: remove tailwindcss devDependency

---

packages/varlet-preset-tailwindcss/src/index.ts

refactor(preset-tailwindcss): rename preset varlet colors

---

packages/varlet-cli/template/generators/config/i18n/sfc/src/button/Button.vue
packages/varlet-cli/template/generators/config/i18n/sfc/src/locale/en-US.ts
packages/varlet-cli/template/generators/config/i18n/sfc/src/locale/index.ts
packages/varlet-cli/template/generators/config/i18n/sfc/src/locale/zh-CN.ts
packages/varlet-cli/template/generators/config/i18n/tsx/src/button/Button.tsx
packages/varlet-cli/template/generators/config/i18n/tsx/src/locale/en-US.ts
packages/varlet-cli/template/generators/config/i18n/tsx/src/locale/index.ts
packages/varlet-cli/template/generators/config/i18n/tsx/src/locale/zh-CN.ts

fix(cli/gen): replace pack

---

packages/varlet-ui/src/cell/docs/en-US.md
packages/varlet-ui/src/cell/docs/zh-CN.md
packages/varlet-ui/src/cell/props.ts
packages/varlet-ui/types/cell.d.ts

fix(cell): limit the type of title to string

---

packages/varlet-ui/src/card/docs/en-US.md
packages/varlet-ui/src/card/docs/zh-CN.md

docs(card): add missing v-model directive

---

packages/varlet-ui/src/swipe/docs/en-US.md
packages/varlet-ui/src/swipe/docs/zh-CN.md

docs(swipe): optimize the description of navigation prop

---

packages/varlet-ui/src/result/Result.vue
packages/varlet-ui/src/result/Success.vue
packages/varlet-ui/src/result/docs/en-US.md
packages/varlet-ui/src/result/docs/zh-CN.md

refactor(result): optimize code and docs

---

packages/varlet-ui/src/image-preview/docs/en-US.md
packages/varlet-ui/src/image-preview/docs/zh-CN.md

docs(image-preview): add missing v-model directive

---

README.md
README.zh-CN.md
packages/varlet-ui/README.md
packages/varlet-ui/README.zh-CN.md

docs: remove gzip image and optimize description

---

packages/varlet-ui/src/image/docs/en-US.md
packages/varlet-ui/src/image/docs/zh-CN.md

docs(image): correct the default value of radius prop

---

packages/varlet-ui/src/switch/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/switch/__tests__/index.spec.js

test(switch): optimize test case

---

packages/varlet-ui/src/fab/example/index.vue

style(fab): remove useless css style

---

packages/varlet-ui/types/styleVars.d.ts

types(switch): update styleVars

---

packages/varlet-ui/src/menu/usePopover.ts

style(menu): format code

---

packages/varlet-ui/src/avatar-group/AvatarGroup.vue

refactor(avatar-group): remove useless return

---

packages/varlet-ui/src/time-picker/clock.vue

fix(time-picker): update allow time when the value changed

---

packages/varlet-ui/src/date-picker/src/year-picker-panel.vue

refactor(date-picker): optimize code

---

packages/varlet-ui/src/divider/Divider.vue

perf(divider): improve accessibility

---

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/slider/Slider.vue
packages/varlet-ui/src/slider/props.ts

perf(slider): improve accessibility

---

packages/varlet-ui/src/ellipsis/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/tooltip/Tooltip.vue
packages/varlet-ui/src/tooltip/__tests__/__snapshots__/index.spec.js.snap

perf(tooltip): improve accessibility

---

packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/switch/Switch.vue
packages/varlet-ui/src/switch/__tests__/__snapshots__/index.spec.js.snap

perf(switch): improve accessibility

---

packages/varlet-ui/src/slider/Slider.vue

refactor(slider): optimize code

---

packages/varlet-ui/src/breadcrumb/Breadcrumb.vue
packages/varlet-ui/src/breadcrumbs/Breadcrumbs.vue
packages/varlet-ui/src/breadcrumbs/__tests__/__snapshots__/index.spec.js.snap

perf(breadcrumbs): improve accessibility

---

packages/varlet-ui/src/image-preview/__tests__/__snapshots__/component.spec.js.snap
packages/varlet-ui/src/swipe-item/SwipeItem.vue
packages/varlet-ui/src/swipe/Swipe.vue
packages/varlet-ui/src/swipe/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/swipe/__tests__/index.spec.js
packages/varlet-ui/src/swipe/provide.ts

perf(swipe): improve accessibility

---

packages/varlet-ui/src/collapse-item/CollapseItem.vue
packages/varlet-ui/src/collapse-item/collapseItem.less
packages/varlet-ui/src/collapse/Collapse.vue
packages/varlet-ui/src/collapse/provide.ts

perf(collapse): improve accessibility

---

packages/varlet-ui/src/progress/Progress.vue
packages/varlet-ui/src/progress/__tests__/__snapshots__/index.spec.js.snap

perf(progress): improve accessibility

---

README.md
README.zh-CN.md
packages/varlet-ui/README.md
packages/varlet-ui/README.zh-CN.md
packages/varlet-ui/docs/home.en-US.md
packages/varlet-ui/docs/home.zh-CN.md

docs: update readme and site features

---

packages/varlet-ui/src/locale/index.ts

`/varlet-ui/src/date-picker/DatePicker.vue`类型报错

types: type of t's return value

---

packages/varlet-ui/src/themes/docs/en-US.md

docs(themes): typo

---

packages/varlet-ui/src/switch/Switch.vue
packages/varlet-ui/src/switch/__tests__/index.spec.js
packages/varlet-ui/src/switch/docs/en-US.md
packages/varlet-ui/src/switch/docs/zh-CN.md
packages/varlet-ui/src/switch/props.ts
packages/varlet-ui/types/switch.d.ts

feat(switch): support buttonElevation

---

packages/varlet-cli/src/node/config/varlet.default.config.ts

refactor(cli): remove useless import

---

packages/varlet-cli/site/index.html
packages/varlet-cli/site/mobile.html
packages/varlet-cli/src/node/config/vite.config.ts
packages/varlet-vite-plugins/src/html.ts

Provide configuration to add scripts tag into site/index.html

feat(cli): config of adding custom content into index.html

---

packages/varlet-ui/src/pagination/pagination.less
packages/varlet-ui/src/step/step.less
packages/varlet-ui/src/time-picker/timePicker.less
packages/varlet-ui/varlet.config.mjs

Provide more isolated mixin name for style files.
close #1619

refactor(style): isolate mixin name

---

packages/varlet-ui/src/form/docs/en-US.md
packages/varlet-ui/src/form/docs/zh-CN.md
packages/varlet-ui/src/form/example/index.vue
packages/varlet-ui/src/form/example/locale/en-US.ts
packages/varlet-ui/src/form/example/locale/zh-CN.ts

docs(form): improve form example

---

README.md
README.zh-CN.md
packages/varlet-ui/README.md
packages/varlet-ui/README.zh-CN.md
packages/varlet-ui/docs/home.en-US.md
packages/varlet-ui/docs/home.zh-CN.md

docs: Add a template project.
[vue3-varlet-mobile](https://github.com/easy-temps/vue3-varlet-mobile) | `基于 Vue 3 和 Varlet 组件库的移动模板` |

docs: Add a template project

---

packages/varlet-ui/src/utils/shared.ts

refactor(utils): optimize code of padStart function

---

packages/varlet-ui/src/checkbox-group/docs/en-US.md
packages/varlet-ui/src/checkbox-group/docs/zh-CN.md

docs(checkbox-group): optimize label type

---

packages/varlet-cli/README.md
packages/varlet-cli/README.zh-CN.md
packages/varlet-cli/src/node/config/varlet.config.ts
packages/varlet-cli/src/node/config/vite.config.ts
packages/varlet-ui/docs/cli.en-US.md
packages/varlet-ui/docs/cli.zh-CN.md

feat(cli): support server.proxy

---

packages/varlet-ui/src/checkbox-group/CheckboxGroup.vue
packages/varlet-ui/src/checkbox-group/props.ts
packages/varlet-ui/types/checkboxGroup.d.ts

fix(checkbox-group): set option label and value to be required

---

packages/varlet-ui/src/uploader/Uploader.vue

fix(uploader): add missing ripple less file import

---

packages/varlet-ui/src/paper/Paper.vue

fix(paper): add missing ripple less file import

---

packages/varlet-ui/src/checkbox-group/CheckboxGroup.vue
packages/varlet-ui/src/checkbox-group/CheckboxGroupOption.tsx
packages/varlet-ui/src/checkbox-group/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/checkbox-group/__tests__/index.spec.js
packages/varlet-ui/src/checkbox-group/docs/en-US.md
packages/varlet-ui/src/checkbox-group/docs/zh-CN.md
packages/varlet-ui/src/checkbox-group/example/index.vue
packages/varlet-ui/src/checkbox-group/example/locale/en-US.ts
packages/varlet-ui/src/checkbox-group/example/locale/zh-CN.ts
packages/varlet-ui/src/checkbox-group/props.ts
packages/varlet-ui/src/checkbox/Checkbox.vue
packages/varlet-ui/src/checkbox/docs/en-US.md
packages/varlet-ui/src/checkbox/docs/zh-CN.md
packages/varlet-ui/types/checkbox.d.ts
packages/varlet-ui/types/checkboxGroup.d.ts

feat(checkbox-group): support label-key and value-key prop and export checked for default slot

---

packages/varlet-ui/varlet.config.mjs

docs: Update varlet.config.mjs

---

packages/varlet-ui/src/cell/cell.less

fix(cell): disable tap highlights on iOS

---

packages/varlet-ui/src/bottom-navigation/BottomNavigation.vue

refactor(bottom-navigation): optimize code

---

packages/varlet-ui/src/paper/paper.less

fix(paper): disable tap highlights on iOS

---

packages/varlet-ui/src/link/link.less

fix(link): disable tap highlights on iOS

---

packages/varlet-ui/src/ellipsis/ellipsis.less

fix(ellipsis): disable tap highlights on iOS

---

packages/varlet-ui/src/checkbox-group/__tests__/index.spec.js
packages/varlet-ui/src/checkbox/Checkbox.vue

fix(checkbox): don't trigger click event when clicking validate message

---

packages/varlet-ui/src/avatar/avatar.less

fix(avatar): disable tap highlights on iOS

---

packages/varlet-cli/src/node/compiler/compileStyleVars.ts
packages/varlet-ui/types/styleVars.d.ts

perf(cli): reduce the size of styleVars type

---

packages/varlet-ui/src/swipe-item/SwipeItem.vue
packages/varlet-ui/src/swipe-item/provide.ts
packages/varlet-ui/src/swipe-item/swipeItem.less
packages/varlet-ui/src/swipe/Swipe.vue
packages/varlet-ui/src/swipe/__tests__/index.spec.js

feat(swipe): support keyboard arrowLeft and arrowRight

---

packages/varlet-ui/src/checkbox-group/__tests__/index.spec.js
packages/varlet-ui/src/radio-group/__tests__/index.spec.js

test(radio, checkbox): add test case about default slot checked status

---

packages/varlet-cli/site/mobile/App.vue
packages/varlet-cli/site/mobile/AppHome.vue
packages/varlet-cli/site/pc/Layout.vue
packages/varlet-ui/src/back-top/backTop.less
packages/varlet-ui/src/button/button.less
packages/varlet-ui/src/checkbox/checkbox.less
packages/varlet-ui/src/chip/chip.less
packages/varlet-ui/src/collapse-item/collapseItem.less
packages/varlet-ui/src/counter/counter.less
packages/varlet-ui/src/date-picker/date-picker.less
packages/varlet-ui/src/icon/example/index.vue
packages/varlet-ui/src/index-bar/indexBar.less
packages/varlet-ui/src/list/list.less
packages/varlet-ui/src/menu-option/menuOption.less
packages/varlet-ui/src/option/option.less
packages/varlet-ui/src/radio/radio.less
packages/varlet-ui/src/rate/rate.less
packages/varlet-ui/src/ripple/docs/en-US.md
packages/varlet-ui/src/ripple/docs/zh-CN.md
packages/varlet-ui/src/ripple/example/index.vue
packages/varlet-ui/src/slider/slider.less
packages/varlet-ui/src/step/step.less
packages/varlet-ui/src/switch/switch.less
packages/varlet-ui/src/tab/tab.less
packages/varlet-ui/src/time-picker/timePicker.less
packages/varlet-ui/src/uploader/uploader.less

refactor: replace rgba(0, 0, 0, 0)  with transparent

---

packages/varlet-ui/src/fab/Fab.tsx

types(fab): add type for click function

---

packages/varlet-ui/src/app-bar/AppBar.vue
packages/varlet-ui/src/bottom-navigation/BottomNavigation.vue

refactor(app-bar, bottom-navigation): optimize code

---

packages/varlet-cli/src/node/compiler/compileTypes.ts

refactor(cli): optimize compile type command code

---

packages/varlet-ui/docs/migrationGuide.en-US.md

docs(site): typo

---

packages/varlet-ui/src/menu-option/MenuOption.vue
packages/varlet-ui/src/menu-option/docs/en-US.md
packages/varlet-ui/src/menu-option/docs/zh-CN.md
packages/varlet-ui/src/menu-option/props.ts
packages/varlet-ui/src/menu-select/docs/en-US.md
packages/varlet-ui/src/menu-select/docs/zh-CN.md
packages/varlet-ui/types/menuOption.d.ts

feat(menu-option): support ripple

---

packages/varlet-ui/src/option/Option.vue

fix(option): add missing style import and remove useless import

---

packages/varlet-ui/src/chip/Chip.vue
packages/varlet-ui/src/chip/__tests__/index.spec.js
packages/varlet-ui/src/chip/docs/en-US.md
packages/varlet-ui/src/chip/docs/zh-CN.md
packages/varlet-ui/src/chip/props.ts
packages/varlet-ui/types/chip.d.ts

feat(chip): support elevation

---

packages/varlet-ui/src/chip/docs/en-US.md
packages/varlet-ui/src/chip/docs/zh-CN.md
packages/varlet-ui/src/menu-option/docs/en-US.md
packages/varlet-ui/src/menu-option/docs/zh-CN.md
packages/varlet-ui/src/menu-select/docs/en-US.md
packages/varlet-ui/src/menu-select/docs/zh-CN.md
packages/varlet-ui/src/snackbar/docs/en-US.md
packages/varlet-ui/src/snackbar/docs/zh-CN.md

docs(ui): add version

---

packages/varlet-ui/src/themes/__tests__/__snapshots__/index.spec.js.snap

test(theme): update snapshot

---

packages/varlet-ui/src/icon/docs/en-US.md
packages/varlet-ui/src/icon/docs/zh-CN.md
packages/varlet-ui/src/icon/example/index.vue
packages/varlet-ui/src/menu/example/index.vue
packages/varlet-ui/src/popup/example/index.vue
packages/varlet-ui/src/tooltip/example/index.vue

docs: optimize example code

---

packages/varlet-ui/src/dialog/__tests__/__snapshots__/component.spec.js.snap
packages/varlet-ui/src/dialog/__tests__/component.spec.js

test(dialog): complete test cases

---

packages/varlet-ui/src/dialog/__tests__/__snapshots__/component.spec.js.snap
packages/varlet-ui/src/dialog/__tests__/component.spec.js

test(dialog): add missing components for default slot case

---

packages/varlet-ui/src/input/Input.vue
packages/varlet-ui/src/input/__tests__/index.spec.js
packages/varlet-ui/src/input/docs/en-US.md
packages/varlet-ui/src/input/docs/zh-CN.md
packages/varlet-ui/src/input/example/index.vue
packages/varlet-ui/src/input/example/locale/en-US.ts
packages/varlet-ui/src/input/example/locale/zh-CN.ts

fix(input): trim value after blurring while setting trim modifier

---

packages/varlet-ui/src/input/example/index.vue

docs(input): typo

---

packages/varlet-ui/src/select/docs/en-US.md
packages/varlet-ui/src/select/docs/zh-CN.md

docs(select): optimize docs

---

packages/varlet-ui/src/utils/components.ts

fix: reset last validation before trigger validate event

---

packages/varlet-ui/src/input/Input.vue
packages/varlet-ui/src/input/docs/en-US.md
packages/varlet-ui/src/input/docs/zh-CN.md
packages/varlet-ui/src/input/example/index.vue
packages/varlet-ui/src/input/example/locale/en-US.ts
packages/varlet-ui/src/input/example/locale/zh-CN.ts
packages/varlet-ui/src/input/props.ts
packages/varlet-ui/types/input.d.ts

Input component support  decimal point keyboard
close #1702 

feat(Input): Support decimal point keyboard

---

packages/varlet-ui/src/input/docs/en-US.md
packages/varlet-ui/src/input/docs/zh-CN.md
packages/varlet-ui/src/input/example/index.vue
packages/varlet-ui/src/input/example/locale/en-US.ts
packages/varlet-ui/src/input/example/locale/zh-CN.ts

docs(input): optimize docs

---

packages/varlet-ui/src/themes/docs/en-US.md
packages/varlet-ui/src/themes/docs/zh-CN.md
packages/varlet-ui/src/themes/example/index.vue

docs(themes): optimize docs

---

packages/varlet-ui/src/context/lock.ts
packages/varlet-ui/src/styles/common.less

refactor(styles): remove useless common style

---

packages/varlet-preset-tailwindcss/src/index.ts
packages/varlet-preset-unocss/src/index.ts

refactor: remove opacity for preset

---

packages/varlet-ui/src/menu-select/docs/en-US.md
packages/varlet-ui/src/menu-select/docs/zh-CN.md

docs(menu-select): typo

---

packages/varlet-ui/src/input/docs/en-US.md
packages/varlet-ui/src/input/docs/zh-CN.md
packages/varlet-ui/src/input/example/index.vue

docs(input): optimize disabled example

---

packages/varlet-ui/src/popup/Popup.tsx
packages/varlet-ui/src/popup/__tests__/index.spec.js
packages/varlet-ui/src/popup/docs/en-US.md
packages/varlet-ui/src/popup/docs/zh-CN.md
packages/varlet-ui/src/popup/props.ts
packages/varlet-ui/types/popup.d.ts

feat(popup): support zIndex

---

packages/varlet-ui/src/picker/Picker.vue
packages/varlet-ui/src/picker/__tests__/__snapshots__/component.spec.js.snap
packages/varlet-ui/src/picker/__tests__/component.spec.js
packages/varlet-ui/src/picker/docs/en-US.md
packages/varlet-ui/src/picker/docs/zh-CN.md
packages/varlet-ui/src/picker/example/index.vue
packages/varlet-ui/src/picker/example/locale/en-US.ts
packages/varlet-ui/src/picker/example/locale/zh-CN.ts
packages/varlet-ui/src/picker/index.ts
packages/varlet-ui/src/picker/props.ts
packages/varlet-ui/types/picker.d.ts

support columnsNum prop for Picker(include multiple column mode and cascade column mode).
close #1712
wiki link for the technical solution: [technical solution link](https://www.yuque.com/oriheart/tqbfcp/angcwsippwzlx9y3?singleDoc)

feat(picker): support columnsCount

---

packages/varlet-ui/src/space/Space.tsx

refactor(space): remove unused import

---

packages/varlet-cli/package.json
pnpm-lock.yaml

chore: remove lodash-es

---

.github/workflows/pkg.pr.new.yml

Should be need to install this [app](https://github.com/apps/pkg-pr-new) before you can use

chore(ci): pkg.pr.new

---

packages/varlet-ui/src/checkbox-group/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/checkbox-group/__tests__/index.spec.js
packages/varlet-ui/src/counter/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/counter/__tests__/index.spec.js
packages/varlet-ui/src/form/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/form/__tests__/index.spec.js
packages/varlet-ui/src/input/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/input/__tests__/index.spec.js
packages/varlet-ui/src/radio-group/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/radio-group/__tests__/index.spec.js
packages/varlet-ui/src/rate/__tests__/index.spec.js
packages/varlet-ui/src/select/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/select/__tests__/index.spec.js
packages/varlet-ui/src/style-provider/__tests__/index.spec.js
packages/varlet-ui/src/time-picker/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/time-picker/__tests__/index.spec.js
packages/varlet-ui/src/uploader/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/uploader/__tests__/index.spec.js

test(ui): switch error message for chinese to english

---

packages/varlet-ui/src/form-details/__tests__/index.spec.js

Update form detail component test case

test(form-details): complete test cases

---

packages/varlet-ui/src/form/__tests__/index.spec.js
packages/varlet-ui/src/form/docs/en-US.md
packages/varlet-ui/src/form/docs/zh-CN.md
packages/varlet-ui/src/form/example/CustomFormComponent.vue

docs(form): optimize example code

---

packages/varlet-ui/types/input.d.ts

types(input): add missing line prop type

---

packages/varlet-cli/template/create/[componentName].d.ts.ejs

feat(cli): support generate component type file for create command

---

packages/varlet-ui/src/auto-complete/AutoComplete.vue
packages/varlet-ui/src/form/__tests__/index.spec.js
packages/varlet-ui/src/radio-group/RadioGroup.vue
packages/varlet-ui/types/autoComplete.d.ts

refactor(auto-complete): remove duplicate form details style import

---

package.json
packages/varlet-cli/package.json
packages/varlet-cli/src/node/commands/lint.ts
packages/varlet-cli/src/node/commands/preview.ts
packages/varlet-cli/src/node/commands/test.ts
pnpm-lock.yaml
scripts/build.mjs

Using `tinyexec` replace `execa`.

feat: using tinyexec

---

packages/varlet-ui/src/tooltip/__tests__/index.spec.js

test(tooltip): unmount the application from the DOM

---

packages/varlet-ui/src/tooltip/docs/en-US.md
packages/varlet-ui/src/tooltip/docs/zh-CN.md
packages/varlet-ui/src/tooltip/example/index.vue

docs(tooltip): optimize disabled example

---

packages/varlet-ui/src/tooltip/Tooltip.vue
packages/varlet-ui/src/tooltip/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/tooltip/__tests__/index.spec.js
packages/varlet-ui/src/tooltip/docs/en-US.md
packages/varlet-ui/src/tooltip/docs/zh-CN.md
packages/varlet-ui/src/tooltip/example/index.vue
packages/varlet-ui/src/tooltip/props.ts
packages/varlet-ui/types/tooltip.d.ts

The tooltip component supports textColor.
close #1749.

feat(tooltip): support textColor

---

packages/varlet-ui/src/select/__tests__/index.spec.js

test(select): unmount the application form the DOM

---

packages/varlet-cli/src/module.d.ts
packages/varlet-cli/src/node/compiler/compileStyle.ts

内部项目改成了支持scss
```scss
@import '@pui/icons/dist/css/pui-icons';
```
会显示找不到路径
根据sass官网文档修改支持了这种引用，简化了用法，本身就支持ts的类型，所以去掉了modules.d.ts的声明

fix(complier): fix scss @import node_modules icons

---

packages/varlet-ui/docs/zodValidation.en-US.md
packages/varlet-ui/docs/zodValidation.zh-CN.md
packages/varlet-ui/src/auto-complete/docs/zh-CN.md
packages/varlet-ui/src/radio-group/docs/zh-CN.md
packages/varlet-ui/src/radio-group/example/index.vue

docs(zod): optimize docs

---

packages/varlet-cli/package.json
packages/varlet-cli/src/node/commands/create.ts
packages/varlet-cli/src/node/commands/gen.ts
pnpm-lock.yaml

refactor: migrate from inquirer to @inquirer/prompts

---

packages/varlet-ui/src/col/Col.vue
packages/varlet-ui/src/col/provide.ts
packages/varlet-ui/src/row/Row.vue
packages/varlet-ui/src/row/provide.ts

row与col的通讯执行过多的没必要执行的函数，优化只有row有变化的时候col重新设定`padding`

feat(row): optimize component communication

---

packages/varlet-ui/src/row/provide.ts

types(row): correct childProvider type

---

packages/varlet-cli/src/node/config/vite.config.ts
packages/varlet-ui/src/date-picker/DatePicker.vue
packages/varlet-ui/src/date-picker/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/date-picker/__tests__/index.spec.js
packages/varlet-ui/src/date-picker/src/day-picker-panel.vue
packages/varlet-ui/src/date-picker/src/month-picker-panel.vue
packages/varlet-ui/src/date-picker/src/year-picker-panel.vue

fix(date-picker): rerender date panel when max or min changes

---

.prettierignore

chore: ignore tailwindcss and unocss lib folder

---

.eslintrc

chore: ignore tailwindcss and unocss preset lib folders for eslint

---

packages/varlet-ui/src/code/__tests__/index.spec.js
packages/varlet-ui/src/code/docs/en-US.md
packages/varlet-ui/src/code/docs/zh-CN.md
packages/varlet-ui/src/code/example/locale/zh-CN.ts
packages/varlet-ui/src/code/props.ts

docs(code): optimize docs

---

packages/varlet-cli/template/create/[ComponentName].tsx.ejs
packages/varlet-cli/template/create/[ComponentName].vue.ejs

refactor(cli): improve create command template code

---

package.json

chore: remove useless nano-staged option concurrent

---

packages/varlet-ui/src/themes/docs/en-US.md
packages/varlet-ui/src/themes/docs/zh-CN.md

docs(themes): correct theme builder link

---

packages/varlet-ui/types/styleProvider.d.ts

`varlet-ui/types/styleProvider.d.ts`中，移除`ExtractedstyleVars`，直接使用`StyleVars`

types: remove duplicate Stylevars type 

---

packages/varlet-ui/src/alert/index.ts

fix(alert): add props default setter

---

packages/varlet-ui/types/card.d.ts

fix(card): fix CardProps types

---

packages/varlet-ui/src/card/__tests__/index.spec.js
packages/varlet-ui/src/card/props.ts

test(card): add outline test case

---

.prettierignore

chore: ignore playground site folder for prettier

---

.gitignore

chore: clean gitignore

---

packages/varlet-vite-plugins/src/markdown.ts

refactor(vite-plugins): optimize markdown code

---

packages/varlet-cli/README.md
packages/varlet-cli/README.zh-CN.md
packages/varlet-cli/src/node/config/varlet.config.ts
packages/varlet-cli/src/node/config/vite.config.ts

support vite plugin
close #1824 

feat(cli): support vite plugin

---

packages/varlet-vscode-extension/package.json

perf(extension): hidden open webview command in commandPalette

---

packages/varlet-ui/tsconfig.json

refactor(ui): clean tsconfig.json include filed

---

packages/varlet-cli/README.md
packages/varlet-cli/README.zh-CN.md
packages/varlet-cli/lib/node/bin.js
packages/varlet-cli/src/node/bin.ts
packages/varlet-cli/src/node/commands/preview.ts

feat(cli): add port option for preview command

---

packages/varlet-cli/package.json
pnpm-lock.yaml

chore: bump release

---

packages/varlet-ui/src/input/Input.vue
packages/varlet-ui/src/input/__tests__/__snapshots__/index.spec.js.snap
packages/varlet-ui/src/input/__tests__/index.spec.js
packages/varlet-ui/src/input/props.ts
packages/varlet-ui/types/input.d.ts

add aria-label prop in input for accessibility purposes

feat(input): add aria-label prop for accessibility and update tests

---

packages/varlet-ui/types/space.d.ts

fix(type): fix typo

---

packages/varlet-ui/types/radioGroup.d.ts

Correct option type to RadioGroupOption.

types(ui/space): correct option type to RadioGroupOption

---

packages/varlet-ui/src/locale/docs/en-US.md
packages/varlet-ui/src/locale/docs/zh-CN.md
packages/varlet-ui/src/locale/index.ts
packages/varlet-ui/src/locale/ja-JP.d.ts
packages/varlet-ui/src/locale/ja-JP.ts
packages/varlet-ui/types/locale.d.ts

feat(locale): support Japanese language
fix(locale): add lost Farsi to `locale.d.ts`

feat(locale): support Japanese language

---

packages/varlet-ui/src/tabs-items/TabsItems.vue
packages/varlet-ui/src/tabs-items/docs/en-US.md
packages/varlet-ui/src/tabs-items/docs/zh-CN.md
packages/varlet-ui/src/tabs-items/props.ts
packages/varlet-ui/src/tabs/docs/en-US.md
packages/varlet-ui/src/tabs/docs/zh-CN.md

feat(tabs-items): support animated

---

README.md
README.zh-CN.md
packages/varlet-ui/README.md
packages/varlet-ui/README.zh-CN.md
packages/varlet-ui/docs/home.en-US.md
packages/varlet-ui/docs/home.zh-CN.md

docs: update vue3-varlet-mobile link

---

packages/varlet-ui/types/skeleton.d.ts

fix(skeleton): use correct component type

---

packages/varlet-ui/src/input/Input.vue
packages/varlet-ui/src/input/docs/en-US.md
packages/varlet-ui/src/input/docs/zh-CN.md
packages/varlet-ui/src/input/example/index.vue
packages/varlet-ui/src/input/example/locale/en-US.ts
packages/varlet-ui/src/input/example/locale/zh-CN.ts
packages/varlet-ui/src/input/props.ts
packages/varlet-ui/types/input.d.ts

Change Information ✨
•	Added autoFill prop for Input component to resolve the issue where username cannot be autofilled when using password inputs.
•	Updated documentation accordingly.

feat(ui/input): add  new feature in the ui/input scope
